---
title: "Monthly"
author: "Dylan Berneman"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(dplyr)
install.packages("plotrix")
library(plotrix)
library(ggplot2)
library(lubridate)
install.packages("ggrepel")
library(ggrepel)
library(readxl)
install.packages("gridExtra")
library(gridExtra)
install.packages("cowplot")
library(cowplot)
install.packages("ggpubr")
library(ggpubr)
```


# Data
```{r}
Monthly_Data <- read_excel("Project 2 Historical Data.xlsx", 
    sheet = "60-40 Returns Monthly", range = "B10:D1174")

# IB
IB <- read_excel("Project 2 Historical Data.xlsx",
    range = "AO11:AR1175", col_types = c("numeric",
        "skip", "skip", "numeric"))

colnames(Monthly_Data) = c("Date", "Large_Cap", "Fixed")

IB["Date"] = Monthly_Data$Date 
IB = IB[,c(3,1:2)]
colnames(IB) = c("Date", "t_bill", "inflation")
IB_plus = IB
IB_plus[,2:3] = 1 + IB_plus[,2:3]

vect0 = vector()
for(i in 0:100){
  vect0 = append(vect0, paste0("Large Cap: ", i, "%,  ", "Fixed: ", 100-i, "%"))}

Monthly_Data_plus = Monthly_Data
Monthly_Data_plus[,2:3] = Monthly_Data[,2:3]+1

# 12 month period
Yearly_Data = Monthly_Data
Yearly_IB = IB
for(i in 2:3){
  for(j in 1:1153){
    x=j
    y=x+11
    Yearly_Data[j,i] = prod(Monthly_Data_plus[x:y, i]) - 1
    Yearly_IB[j,i] = prod(IB_plus[x:y, i]) - 1}}
Yearly_Data = Yearly_Data[1:1153,]
Yearly_IB = Yearly_IB[1:1153,]

# 10 year period
Yearly_Data10 = Monthly_Data
Yearly_IB10 = IB
for(i in 2:3){
  for(j in 1:1045){
    x=j
    y=x+119
    Yearly_Data10[j,i] = prod(Monthly_Data_plus[x:y, i]) - 1
    Yearly_IB10[j,i] = prod(IB_plus[x:y, i]) - 1}}
Yearly_Data10 = Yearly_Data10[1:1045,]
Yearly_IB10 = Yearly_IB10[1:1045,]


# 20 year period
Yearly_Data20 = Monthly_Data
Yearly_IB20 = IB
for(i in 2:3){
  for(j in 1:925){
    x=j
    y=x+239
    Yearly_Data20[j,i] = prod(Monthly_Data_plus[x:y, i]) - 1
    Yearly_IB20[j,i] = prod(IB_plus[x:y, i]) - 1}}
Yearly_Data20 = Yearly_Data20[1:925,]
Yearly_IB20 = Yearly_IB20[1:925,]

# 30 year period
Yearly_Data30 = Monthly_Data
Yearly_IB30 = IB
for(i in 2:3){
  for(j in 1:805){
    x=j
    y=x+359
    Yearly_Data30[j,i] = prod(Monthly_Data_plus[x:y, i])-1
    Yearly_IB30[j,i] = prod(IB_plus[x:y, i])-1}}
Yearly_Data30 = Yearly_Data30[1:805,]
Yearly_IB30 = Yearly_IB30[1:805,]

for(i in 0:100){
  alpha = i/100
  Monthly_Data[paste0("Folio", i)] = NA
  Yearly_Data[paste0("Folio", i)] = NA
  Yearly_Data10[paste0("Folio", i)] = NA
  Yearly_Data20[paste0("Folio", i)] = NA
  Yearly_Data30[paste0("Folio", i)] = NA
  for(j in 1:1164){
    Monthly_Data[j, i+4] = alpha*Monthly_Data$Large_Cap[j] + (1-alpha)*Monthly_Data$Fixed[j]}
  for(j in 1:1153){
    Yearly_Data[j, i+4] = alpha*Yearly_Data$Large_Cap[j] + (1-alpha)*Yearly_Data$Fixed[j]}
  for(j in 1:1045){
    Yearly_Data10[j, i+4] = alpha*Yearly_Data10$Large_Cap[j] + (1-alpha)*Yearly_Data10$Fixed[j]}
  for(j in 1:925){
    Yearly_Data20[j, i+4] = alpha*Yearly_Data20$Large_Cap[j] + (1-alpha)*Yearly_Data20$Fixed[j]}
  for(j in 1:805){
    Yearly_Data30[j, i+4] = alpha*Yearly_Data30$Large_Cap[j] + (1-alpha)*Yearly_Data30$Fixed[j]}}


```

# Monthly Averages
```{r}
# monthly averages
Monthly_Data_plus = Monthly_Data
Monthly_Data_plus[, 4:104] = 1 + Monthly_Data[, 4:104]
IB = IB %>%
  mutate("risk_free" = (1 + IB$t_bill) / (1 + IB$inflation) - 1)
IB_plus = IB
IB_plus[,2:4] = 1 + IB_plus[,2:4]
m_sharpe1 = Monthly_Data[,c(1,4:104)]
m_sharpe1[,2:102] = NA
m_sharpe2 = m_sharpe1

for(i in 0:100){
  Data = cbind(Monthly_Data[,1], IB[,2:4], Monthly_Data[,i+4])
  Data = Data %>%
    mutate("sharpe1" = Data[,5] - Data$risk_free) %>%
    mutate("sharpe2" = Data[,5] - Data$t_bill + Data$inflation)
  m_sharpe1[,i+2] = Data$sharpe1
  m_sharpe2[,i+2] = Data$sharpe2}

m_sharpe1g = m_sharpe1
m_sharpe1g[,2:102] = 1 + m_sharpe1g[,2:102]
m_sharpe2g = m_sharpe2
m_sharpe2g[,2:102] = 1 + m_sharpe2g[,2:102]

# monthly averages, sharpes, and rrr
arith_monthly = data.frame(matrix(ncol=8, nrow = 101))
colnames(arith_monthly) = c("Allocation", "Num", "mean", "std", "rrr", "sharpe1", "sharpe2", "type")
arith_monthly$Allocation = vect0
arith_monthly$type = "Monthly"
arith_monthly$Num = c(seq(0,100,1))
geom_monthly = arith_monthly

for(i in 0:100){
  arith_monthly$mean[i+1] = sum(Monthly_Data[,i+4])/1164
  arith_monthly$std[i+1] = sqrt(var(Monthly_Data[,i+4]))
  arith_monthly$rrr[i+1] = (sum(Monthly_Data[,i+4])/1164)/sqrt(var(Monthly_Data[,i+4]))
  arith_monthly$sharpe1[i+1] = (sum(m_sharpe1[,i+2])/1164)/arith_monthly$std[i+1]
  arith_monthly$sharpe2[i+1] = (sum(m_sharpe2[,i+2])/1164)/arith_monthly$std[i+1]
  geom_monthly$mean[i+1] = prod(Monthly_Data_plus[,i+4])^(1/1164)-1
  geom_monthly$std[i+1] = sqrt(var(Monthly_Data_plus[,i+4]))
  geom_monthly$rrr[i+1] = (prod(Monthly_Data_plus[,i+4])^(1/1164)-1)/sqrt(var(Monthly_Data_plus[,i+4]))
  geom_monthly$sharpe1[i+1] = (prod(m_sharpe1g[,i+2])^(1/1164)-1)/geom_monthly$std[i+1]
  geom_monthly$sharpe2[i+1] = (prod(m_sharpe2g[,i+2])^(1/1164)-1)/geom_monthly$std[i+1]
  }

arith_monthly$Allocation = factor(arith_monthly$Allocation, levels = c(arith_monthly$Allocation))
geom_monthly$Allocation = factor(geom_monthly$Allocation, levels = c(geom_monthly$Allocation))

write.csv(arith_monthly, "arith_monthly.csv", col.names=colnames(arith_monthly), row.names = FALSE, quote=TRUE)
write.csv(geom_monthly, "geom_monthly.csv", col.names=colnames(geom_monthly), row.names = FALSE, quote=TRUE)
```

# 12 Month Averages
```{r}
# 12 month averages
Yearly_Data_plus = Yearly_Data
Yearly_Data_plus[, 4:104] = 1 + Yearly_Data[, 4:104]
Yearly_IB = Yearly_IB %>%
  mutate("risk_free" = (1 + Yearly_IB$t_bill) / (1 + Yearly_IB$inflation) - 1)
Yearly_IB_plus = Yearly_IB
Yearly_IB_plus[,2:4] = 1 + Yearly_IB_plus[,2:4]
y_sharpe1 = Yearly_Data[,c(1,4:104)]
y_sharpe1[,2:102] = NA
y_sharpe2 = y_sharpe1

for(i in 0:100){
  Data = cbind(Yearly_Data[,1], Yearly_IB[,2:4], Yearly_Data[,i+4])
  Data = Data %>%
    mutate("sharpe1" = Data[,5] - Data$risk_free) %>%
    mutate("sharpe2" = Data[,5] - Data$t_bill + Data$inflation)
  y_sharpe1[,i+2] = Data$sharpe1
  y_sharpe2[,i+2] = Data$sharpe2}

y_sharpe1g = y_sharpe1
y_sharpe1g[,2:102] = 1 + y_sharpe1g[,2:102]
y_sharpe2g = y_sharpe2
y_sharpe2g[,2:102] = 1 + y_sharpe2g[,2:102]

# Yearly averages, sharpes, and rrr
arith_Yearly = data.frame(matrix(ncol=8, nrow = 101))
colnames(arith_Yearly) = c("Allocation", "Num", "mean", "std", "rrr", "sharpe1", "sharpe2", "type")
arith_Yearly$Allocation = vect0
arith_Yearly$type = "12 Months"
arith_Yearly$Num = c(seq(0,100,1))
geom_Yearly = arith_Yearly

for(i in 0:100){
  arith_Yearly$mean[i+1] = sum(Yearly_Data[,i+4])/1153
  arith_Yearly$std[i+1] = sqrt(var(Yearly_Data[,i+4]))
  arith_Yearly$rrr[i+1] = (sum(Yearly_Data[,i+4])/1153)/sqrt(var(Yearly_Data[,i+4]))
  arith_Yearly$sharpe1[i+1] = (sum(y_sharpe1[,i+2])/1153)/arith_Yearly$std[i+1]
  arith_Yearly$sharpe2[i+1] = (sum(y_sharpe2[,i+2])/1153)/arith_Yearly$std[i+1]
  geom_Yearly$mean[i+1] = prod(Yearly_Data_plus[,i+4])^(1/1153)-1
  geom_Yearly$std[i+1] = sqrt(var(Yearly_Data_plus[,i+4]))
  geom_Yearly$rrr[i+1] = (prod(Yearly_Data_plus[,i+4])^(1/1153)-1)/sqrt(var(Yearly_Data_plus[,i+4]))
  geom_Yearly$sharpe1[i+1] = (prod(y_sharpe1g[,i+2])^(1/1153)-1)/geom_Yearly$std[i+1]
  geom_Yearly$sharpe2[i+1] = (prod(y_sharpe2g[,i+2])^(1/1153)-1)/geom_Yearly$std[i+1]
  }

arith_Yearly$Allocation = factor(arith_Yearly$Allocation, levels = c(arith_Yearly$Allocation))
geom_Yearly$Allocation = factor(geom_Yearly$Allocation, levels = c(geom_Yearly$Allocation))


write.csv(arith_Yearly, "arith_Yearly.csv", col.names=colnames(arith_Yearly), row.names = FALSE, quote=TRUE)
write.csv(geom_Yearly, "geom_Yearly.csv", col.names=colnames(geom_Yearly), row.names = FALSE, quote=TRUE)
```


# 120 Month Averages
```{r}
# 12 month averages
Yearly_Data10_plus = Yearly_Data10
Yearly_Data10_plus[, 4:104] = 1 + Yearly_Data10[, 4:104]
Yearly_Data10_120 = Yearly_Data10_plus
Yearly_Data10_120[,4:104] = Yearly_Data10_120[,4:104]^(1/120)
Yearly_IB10 = Yearly_IB10 %>%
  mutate("risk_free" = (1 + Yearly_IB10$t_bill) / (1 + Yearly_IB10$inflation) - 1)
Yearly_IB10_plus = Yearly_IB10
Yearly_IB10_plus[,2:4] = 1 + Yearly_IB10_plus[,2:4]
y10_sharpe1 = Yearly_Data10[,c(1,4:104)]
y10_sharpe1[,2:102] = NA
y10_sharpe2 = y10_sharpe1
std_10 = data.frame(matrix(ncol=4, nrow=101))
colnames(std_10) = c("Allocation", "Sharpe1", "Sharpe2", "Sharpe3")
std_10$Allocation = vect0
sharpe_choice10 = std_10

for(i in 0:100){
  Data = cbind(Yearly_Data10[,1], Yearly_IB10[,2:4], Yearly_Data10[,i+4])
  Data = Data %>%
    mutate("sharpe1" = Data[,5] - Data$risk_free) %>%
    mutate("sharpe2" = Data[,5] - Data$t_bill + Data$inflation)
  y10_sharpe1[,i+2] = Data$sharpe1
  std_10$Sharpe1[i+1] = sqrt(var(Data$sharpe1))
  y10_sharpe2[,i+2] = Data$sharpe2
  std_10$Sharpe2[i+1] = sqrt(var(Data$sharpe2))}

y10_sharpe1g = y10_sharpe1
y10_sharpe1g[,2:102] = NA
y10_sharpe2g = y10_sharpe1g

for(i in 0:100){
  Data10_sharpe1 = y10_sharpe1[,c(1,i+2)]
  Data10_sharpe1 = Data10_sharpe1 %>%
    mutate("Geom1_120" = (1 + Data10_sharpe1[,2])^(1/120))
  y10_sharpe1g[,i+2] = Data10_sharpe1$Geom1_120[[1]]}


for(i in 0:100){
  Data10_sharpe2 = y10_sharpe2[,c(1,i+2)]
  Data10_sharpe2 = Data10_sharpe2 %>%
    mutate("Geom1_120" = (1 + Data10_sharpe2[,2])^(1/120))
  y10_sharpe2g[,i+2] = Data10_sharpe2$Geom1_120[[1]]}

# Yearly averages, sharpes, and rrr
arith_Yearly10 = data.frame(matrix(ncol=8, nrow = 101))
colnames(arith_Yearly10) = c("Allocation", "Num", "mean", "std", "rrr", "sharpe1", "sharpe2", "type")
arith_Yearly10$Allocation = vect0
arith_Yearly10$type = "120 Months"
arith_Yearly10$Num = c(seq(0,100,1))
geom_Yearly10 = arith_Yearly10

for(i in 0:100){
  arith_Yearly10$mean[i+1] = sum(Yearly_Data10[,i+4])/1045
  arith_Yearly10$std[i+1] = sqrt(var(Yearly_Data10[,i+4]))
  arith_Yearly10$rrr[i+1] = (sum(Yearly_Data10[,i+4])/1045)/sqrt(var(Yearly_Data10[,i+4]))
  arith_Yearly10$sharpe1[i+1] = (sum(y10_sharpe1[,i+2])/1045)/arith_Yearly10$std[i+1]
  arith_Yearly10$sharpe2[i+1] = (sum(y10_sharpe2[,i+2])/1045)/arith_Yearly10$std[i+1]
  geom_Yearly10$mean[i+1] = prod(Yearly_Data10_120[,i+4])^(120/1045)-1
  geom_Yearly10$std[i+1] = sqrt(var(Yearly_Data10_plus[,i+4]))
  geom_Yearly10$rrr[i+1] = (prod(Yearly_Data10_120[,i+4])^(120/1045)-1)/sqrt(var(Yearly_Data10_plus[,i+4]))
  geom_Yearly10$sharpe1[i+1] = (prod(y10_sharpe1g[,i+2])^(120/1045)-1)/geom_Yearly10$std[i+1]
  geom_Yearly10$sharpe2[i+1] = (prod(y10_sharpe2g[,i+2])^(120/1045)-1)/geom_Yearly10$std[i+1]}

arith_Yearly10$Allocation = factor(arith_Yearly10$Allocation, levels = c(arith_Yearly10$Allocation))
geom_Yearly10$Allocation = factor(geom_Yearly10$Allocation, levels = c(geom_Yearly10$Allocation))


write.csv(arith_Yearly10, "arith_Yearly10.csv", col.names=colnames(arith_Yearly10), row.names = FALSE, quote=TRUE)
write.csv(geom_Yearly10, "geom_Yearly10.csv", col.names=colnames(geom_Yearly10), row.names = FALSE, quote=TRUE)
```

# 240 Month Averages
```{r}

Yearly_Data20_plus = Yearly_Data20
Yearly_Data20_plus[, 4:104] = 1 + Yearly_Data20[, 4:104]
Yearly_Data20_240 = Yearly_Data20_plus
Yearly_Data20_240[,4:104] = Yearly_Data20_240[,4:104]^(1/240)
Yearly_IB20 = Yearly_IB20 %>%
  mutate("risk_free" = (1 + Yearly_IB20$t_bill) / (1 + Yearly_IB20$inflation) - 1)
Yearly_IB20_plus = Yearly_IB20
Yearly_IB20_plus[,2:4] = 1 + Yearly_IB20_plus[,2:4]
y20_sharpe1 = Yearly_Data20[,c(1,4:104)]
y20_sharpe1[,2:102] = NA
y20_sharpe2 = y20_sharpe1
std_20 = data.frame(matrix(ncol=4, nrow=101))
colnames(std_20) = c("Allocation", "Sharpe1", "Sharpe2", "Sharpe3")
std_20$Allocation = vect0
sharpe_choice20 = std_20

for(i in 0:100){
  Data = cbind(Yearly_Data20[,1], Yearly_IB20[,2:4], Yearly_Data20[,i+4])
  Data = Data %>%
    mutate("sharpe1" = Data[,5] - Data$risk_free) %>%
    mutate("sharpe2" = Data[,5] - Data$t_bill + Data$inflation)
  y20_sharpe1[,i+2] = Data$sharpe1
  std_20$Sharpe1[i+1] = sqrt(var(Data$sharpe1))
  y20_sharpe2[,i+2] = Data$sharpe2
  std_20$Sharpe2[i+1] = sqrt(var(Data$sharpe2))}

y20_sharpe1g = y20_sharpe1
y20_sharpe1g[,2:102] = NA
y20_sharpe2g = y20_sharpe1g

for(i in 0:100){
  Data20_sharpe1 = y20_sharpe1[,c(1,i+2)]
  Data20_sharpe1 = Data20_sharpe1 %>%
    mutate("Geom1_240" = (1 + Data20_sharpe1[,2])^(1/240))
  y20_sharpe1g[,i+2] = Data20_sharpe1$Geom1_240[[1]]}

for(i in 0:100){
  Data20_sharpe2 = y20_sharpe2[,c(1,i+2)]
  Data20_sharpe2 = Data20_sharpe2 %>%
    mutate("Geom1_240" = (1 + Data20_sharpe2[,2])^(1/240))
  y20_sharpe2g[,i+2] = Data20_sharpe2$Geom1_240[[1]]}


# Yearly averages, sharpes, and rrr
arith_Yearly20 = data.frame(matrix(ncol=8, nrow = 101))
colnames(arith_Yearly20) = c("Allocation", "Num", "mean", "std", "rrr", "sharpe1", "sharpe2", "type")
arith_Yearly20$Allocation = vect0
arith_Yearly20$type = "240 Months"
arith_Yearly20$Num = c(seq(0,100,1))
geom_Yearly20 = arith_Yearly20

for(i in 0:100){
  arith_Yearly20$mean[i+1] = sum(Yearly_Data20[,i+4])/925
  arith_Yearly20$std[i+1] = sqrt(var(Yearly_Data20[,i+4]))
  arith_Yearly20$rrr[i+1] = (sum(Yearly_Data20[,i+4])/925)/sqrt(var(Yearly_Data20[,i+4]))
  arith_Yearly20$sharpe1[i+1] = (sum(y20_sharpe1[,i+2])/925)/arith_Yearly20$std[i+1]
  arith_Yearly20$sharpe2[i+1] = (sum(y20_sharpe2[,i+2])/925)/arith_Yearly20$std[i+1]
  geom_Yearly20$mean[i+1] = prod(Yearly_Data20_240[,i+4])^(240/925)-1
  geom_Yearly20$std[i+1] = sqrt(var(Yearly_Data20_plus[,i+4]))
  geom_Yearly20$rrr[i+1] = (prod(Yearly_Data20_240[,i+4])^(240/925)-1)/sqrt(var(Yearly_Data20_plus[,i+4]))
  geom_Yearly20$sharpe1[i+1] = (prod(y20_sharpe1g[,i+2])^(240/925)-1)/geom_Yearly20$std[i+1]
  geom_Yearly20$sharpe2[i+1] = (prod(y20_sharpe2g[,i+2])^(240/925)-1)/geom_Yearly20$std[i+1]}

arith_Yearly20$Allocation = factor(arith_Yearly20$Allocation, levels = c(arith_Yearly20$Allocation))
geom_Yearly20$Allocation = factor(geom_Yearly20$Allocation, levels = c(geom_Yearly20$Allocation))


write.csv(arith_Yearly20, "arith_Yearly20.csv", col.names=colnames(arith_Yearly20), row.names = FALSE, quote=TRUE)
write.csv(geom_Yearly20, "geom_Yearly20.csv", col.names=colnames(geom_Yearly20), row.names = FALSE, quote=TRUE)
```


# 360 Month Averages
```{r}

Yearly_Data30_plus = Yearly_Data30
Yearly_Data30_plus[, 4:104] = 1 + Yearly_Data30[, 4:104]
Yearly_Data30_360 = Yearly_Data30_plus
Yearly_Data30_360[,4:104] = Yearly_Data30_360[,4:104]^(1/360)
Yearly_IB30 = Yearly_IB30 %>%
  mutate("risk_free" = (1 + Yearly_IB30$t_bill) / (1 + Yearly_IB30$inflation) - 1)
Yearly_IB30_plus = Yearly_IB30
Yearly_IB30_plus[,2:4] = 1 + Yearly_IB30_plus[,2:4]
y30_sharpe1 = Yearly_Data30[,c(1,4:104)]
y30_sharpe1[,2:102] = NA
y30_sharpe2 = y30_sharpe1
std_30 = data.frame(matrix(ncol=4, nrow=101))
colnames(std_30) = c("Allocation", "Sharpe1", "Sharpe2", "Sharpe3")
std_30$Allocation = vect0
sharpe_choice30 = std_30

for(i in 0:100){
  Data = cbind(Yearly_Data30[,1], Yearly_IB30[,2:4], Yearly_Data30[,i+4])
  Data = Data %>%
    mutate("sharpe1" = Data[,5] - Data$risk_free) %>%
    mutate("sharpe2" = Data[,5] - Data$t_bill + Data$inflation)
  y30_sharpe1[,i+2] = Data$sharpe1
  std_30$Sharpe1[i+1] = sqrt(var(Data$sharpe1))
  y30_sharpe2[,i+2] = Data$sharpe2
  std_30$Sharpe2[i+1] = sqrt(var(Data$sharpe2))}

y30_sharpe1g = y30_sharpe1
y30_sharpe1g[,2:102] = NA
y30_sharpe2g = y30_sharpe1g

for(i in 0:100){
  Data30_sharpe1 = y30_sharpe1[,c(1,i+2)]
  Data30_sharpe1 = Data30_sharpe1 %>%
    mutate("Geom1_360" = (1 + Data30_sharpe1[,2])^(1/360))
  y30_sharpe1g[,i+2] = Data30_sharpe1$Geom1_360[[1]]}

for(i in 0:100){
  Data30_sharpe2 = y30_sharpe2[,c(1,i+2)]
  Data30_sharpe2 = Data30_sharpe2 %>%
    mutate("Geom1_360" = (1 + Data30_sharpe2[,2])^(1/360))
  y30_sharpe2g[,i+2] = Data30_sharpe2$Geom1_360[[1]]}

# Yearly averages, sharpes, and rrr
arith_Yearly30 = data.frame(matrix(ncol=8, nrow = 101))
colnames(arith_Yearly30) = c("Allocation", "Num", "mean", "std", "rrr", "sharpe1", "sharpe2", "type")
arith_Yearly30$Allocation = vect0
arith_Yearly30$type = "360 Months"
arith_Yearly30$Num = c(seq(0,100,1))
geom_Yearly30 = arith_Yearly30

for(i in 0:100){
  arith_Yearly30$mean[i+1] = sum(Yearly_Data30[,i+4])/805
  arith_Yearly30$std[i+1] = sqrt(var(Yearly_Data30[,i+4]))
  arith_Yearly30$rrr[i+1] = (sum(Yearly_Data30[,i+4])/805)/sqrt(var(Yearly_Data30[,i+4]))
  arith_Yearly30$sharpe1[i+1] = (sum(y30_sharpe1[,i+2])/805)/arith_Yearly30$std[i+1]
  arith_Yearly30$sharpe2[i+1] = (sum(y30_sharpe2[,i+2])/805)/arith_Yearly30$std[i+1]
  geom_Yearly30$mean[i+1] = prod(Yearly_Data30_360[,i+4])^(360/805)-1
  geom_Yearly30$std[i+1] = sqrt(var(Yearly_Data30_plus[,i+4]))
  geom_Yearly30$rrr[i+1] = (prod(Yearly_Data30_360[,i+4])^(360/805)-1)/sqrt(var(Yearly_Data30_plus[,i+4]))
  geom_Yearly30$sharpe1[i+1] = (prod(y30_sharpe1g[,i+2])^(360/805)-1)/geom_Yearly30$std[i+1]
  geom_Yearly30$sharpe2[i+1] = (prod(y30_sharpe2g[,i+2])^(360/805)-1)/geom_Yearly30$std[i+1]}

arith_Yearly30$Allocation = factor(arith_Yearly30$Allocation, levels = c(arith_Yearly30$Allocation))
geom_Yearly30$Allocation = factor(geom_Yearly30$Allocation, levels = c(geom_Yearly30$Allocation))


write.csv(arith_Yearly30, "arith_Yearly30.csv", col.names=colnames(arith_Yearly30), row.names = FALSE, quote=TRUE)
write.csv(geom_Yearly30, "geom_Yearly30.csv", col.names=colnames(geom_Yearly30), row.names = FALSE, quote=TRUE)

arith = rbind(arith_monthly, arith_Yearly, arith_Yearly10, arith_Yearly20, arith_Yearly30)
geom = rbind(geom_monthly, geom_Yearly, geom_Yearly10, geom_Yearly20, geom_Yearly30)

write.csv(arith, "arith.csv", col.names=colnames(arith), row.names = FALSE, quote=TRUE)
write.csv(geom, "geom.csv", col.names=colnames(geom), row.names = FALSE, quote=TRUE)
```


# Saved data frames and significant points
```{r}
arith_monthly = read.csv("arith_monthly.csv")
geom_monthly = read.csv("geom_monthly.csv")
arith_Yearly = read.csv("arith_Yearly.csv")
geom_Yearly = read.csv("geom_Yearly.csv")
arith_Yearly10 = read.csv("arith_Yearly10.csv")
geom_Yearly10 = read.csv("geom_Yearly10.csv")
arith_Yearly20 = read.csv("arith_Yearly20.csv")
geom_Yearly20 = read.csv("geom_Yearly20.csv")
arith_Yearly30 = read.csv("arith_Yearly30.csv")
geom_Yearly30 = read.csv("geom_Yearly30.csv")
arith = read.csv("arith.csv")
geom = read.csv("geom.csv")


for(i in 1:5){
  if(i==1){
    x = arith_monthly
    x = x %>%
      mutate("Method" = "Arithmetic")
    y = geom_monthly
    y = y %>%
      mutate("Method" = "Geometric")
    frame = rbind(x,y)
    name = "Monthly"}
  if(i==2){
    x = arith_Yearly
    x = x %>%
      mutate("Method" = "Arithmetic")
    y = geom_Yearly
    y = y %>%
      mutate("Method" = "Geometric")
    frame = rbind(x,y)
    name = "Yearly"}
  if(i==3){
    x = arith_Yearly10
    x = x %>%
      mutate("Method" = "Arithmetic")
    y = geom_Yearly10
    y = y %>%
      mutate("Method" = "Geometric")
    frame = rbind(x,y)  
    name = "Yearly_10"}
  if(i==4){
    x = arith_Yearly20
    x = x %>%
      mutate("Method" = "Arithmetic")
    y = geom_Yearly20
    y = y %>%
      mutate("Method" = "Geometric")
    frame = rbind(x,y)
    name = "Yearly_20"}
  if(i==5){
    x = arith_Yearly30
    x = x %>%
      mutate("Method" = "Arithmetic")
    y = geom_Yearly30
    y = y %>%
      mutate("Method" = "Geometric")
    frame = rbind(x,y)
    name = "Yearly_30"}
  stats = frame[,c(1:4,9)]
  min1 = min(stats$std[1:101])
  max1 = max(stats$std[1:101])
  min2 = min(stats$std[102:202])
  max2 = max(stats$std[102:202])
  vect0 = vector()
  vect0 = append(vect0, c(1,61,101))
  for(j in 1:101){
    if(stats$std[[j]] == min1 | stats$std[[j]] == max1){
      vect0 = append(vect0, j)}}
  vect0 = unique(vect0)
  vect0 = sort(vect0)
  vect1 = vector()
  vect1 = append(vect1, c(102,162,202))
  for(j in 102:202){
    if(stats$std[[j]] == min2| stats$std[[j]] == max2){
      vect1 = append(vect1, j)}}
  vect1 = unique(vect1)
  vect1 = sort(vect1)
  vect_sig = vector()
  vect_sig = append(vect_sig, c(vect0,vect1))
  sig_stat1 = stats[c(vect0),]
  sig_stat2 = stats[c(vect1),]
  sig_stat = stats[-c(vect_sig),]
  sig_stat <- sig_stat %>%
    mutate("Rank_std" = NA)
  sig_stat1 <- sig_stat1 %>%
    mutate("Rank_std" = rank(sig_stat1$std))
  sig_stat2 <- sig_stat2 %>%
    mutate("Rank_std" = rank(sig_stat2[,4]))
  sig_stat12 = rbind(sig_stat1, sig_stat2)
  stats = rbind(sig_stat, sig_stat1, sig_stat2)
  stats_A = subset(stats, stats$Method == "Arithmetic")
  stats_G = subset(stats, stats$Method == "Geometric")
  stats_A_num = order(stats_A$Num)
  stats_G_num = order(stats_G$Num)
  stats_A = stats_A[c(stats_A_num),]
  stats_G = stats_G[c(stats_G_num),]
  stats = rbind(stats_A, stats_G)
  stats["Rank_color_std"] = NA
  for(j in 1:202){
    if(is.na(stats$Rank_std[j])){
      stats$Rank_color_std[j] = "black"}
    else{
      if(stats$Rank_std[j] == 1){
        stats$Rank_color_std[j] = "green"}
      else{
        if(stats$Rank_std[j] == 2){
          stats$Rank_color_std[j] = "yellow"}
        else{
          if(stats$Rank_std[j] == 3){
            stats$Rank_color_std[j] = "orange"}
          else{
            if(stats$Rank_std[j] == 4){
              stats$Rank_color_std[j] = "red"}}}}}}
  num = subset(stats[1:101,], stats$std[1:101] == min(stats$std[1:101]))$Num + 1
  num2 = subset(stats[102:202,], stats$std[102:202] == min(stats$std[102:202]))$Num + 1
  stats1 = stats[1:101,]
  stats2 = stats[102:202,]
  stats1= stats1%>%
    mutate("Percent Change: Mean" = round(100*(stats1$mean-(stats1$mean[num]))/(stats1$mean[num]),4)) %>%
    mutate("Percent Change: SD" = round(100*(stats1$std-(stats1$std[num]))/(stats1$std[num]),4))
  stats1 = stats1%>%
    mutate("Mean vs SD Percent Change" = round(stats1$`Percent Change: Mean`/stats1$`Percent Change: SD`,4)) %>%
    mutate("Lower_CI" = stats1$mean - 1.96*stats1$std) %>%
    mutate("Upper_CI" = stats1$mean + 1.96*stats1$std)
  if(i == 1){
    stats1$Rank_color_std[6:13] = "lightblue"}
  if(i == 2){
    stats1$Rank_color_std[8:17] = "lightblue"}
  if(i == 3){
    stats1$Rank_color_std[11:34] = "lightblue"}
  if(i == 4){
    stats1$Rank_color_std[4:35] = "lightblue"}
  if(i == 5){
    stats1$Rank_color_std[c(15:60, 62:66)] = "lightblue"}
  stats1 = stats1 %>%
    mutate("Signif" = stats1$Lower_CI[1:101] == max(stats1$Lower_CI)| stats1$Num[1:101] %in% c(0,60,100))
  stats_signif1 = subset(stats1, stats1$Signif == TRUE)
  stats_Not_signif1 = subset(stats1, stats1$Signif != TRUE)
  stats_signif1 = stats_signif1 %>%
    mutate("Rank_CI" = length(stats_signif1$Signif) + 1 - rank(stats_signif1$Lower_CI))
  stats_Not_signif1 = stats_Not_signif1 %>%
    mutate("Rank_CI" = NA)
  stats1 = rbind(stats_Not_signif1, stats_signif1)
  stats1_num = order(stats1$Num)
  stats1 = stats1[c(stats1_num),]
  stats1 = stats1 %>%
    mutate("Rank_CI_color" = NA)
  if(101 - sum(is.na(stats1$Rank_CI)) == 9){
    for(j in 1:101){
      if(is.na(stats1$Rank_CI[j]) == TRUE){
        stats1$Rank_CI_color[j] = "black"}
      else{
        if(stats1$Rank_CI[j] == 1){
          stats1$Rank_CI_color[j] = "blue"}
        else{
          if(stats1$Rank_CI[j] == 2){
            stats1$Rank_CI_color[j] = "lightblue"}
          else{
            if(stats1$Rank_CI[j] == 3){
              stats1$Rank_CI_color[j] = "aquamarine"}
            else{
              if(stats1$Rank_CI[j] == 4){
                stats1$Rank_CI_color[j] = "lightgreen"}
              else{
                if(stats1$Rank_CI[j] == 5){
                  stats1$Rank_CI_color[j] = "green"}
                else{
                  if(stats1$Rank_CI[j] == 6){
                    stats1$Rank_CI_color[j] = "yellowgreen"}
                  else{
                    if(stats1$Rank_CI[j] == 7){
                      stats1$Rank_CI_color[j] = "yellow"}
                    else{
                      if(stats1$Rank_CI[j] == 8){
                        stats1$Rank_CI_color[j] = "orange"}
                      else{
                        if(stats1$Rank_CI[j] == 9){
                          stats1$Rank_CI_color[j] = "red"}}}}}}}}}}}}
  if(101 - sum(is.na(stats1$Rank_CI)) == 8){
    for(j in 1:101){
      if(is.na(stats1$Rank_CI[j]) == TRUE){
        stats1$Rank_CI_color[j] = "black"}
      else{
        if(stats1$Rank_CI[j] == 1){
          stats1$Rank_CI_color[j] = "blue"}
        else{
          if(stats1$Rank_CI[j] == 2){
            stats1$Rank_CI_color[j] = "lightblue"}
          else{
            if(stats1$Rank_CI[j] == 3){
              stats1$Rank_CI_color[j] = "lightgreen"}
            else{
              if(stats1$Rank_CI[j] == 4){
                stats1$Rank_CI_color[j] = "green"}
              else{
                if(stats1$Rank_CI[j] == 5){
                  stats1$Rank_CI_color[j] = "yellowgreen"}
                else{
                  if(stats1$Rank_CI[j] == 6){
                    stats1$Rank_CI_color[j] = "yellow"}
                  else{
                    if(stats1$Rank_CI[j] == 7){
                      stats1$Rank_CI_color[j] = "orange"}
                    else{
                      if(stats1$Rank_CI[j] == 8){
                        stats1$Rank_CI_color[j] = "red"}}}}}}}}}}}
  if(101 - sum(is.na(stats1$Rank_CI)) == 7){
    for(j in 1:101){
      if(is.na(stats1$Rank_CI[j]) == TRUE){
        stats1$Rank_CI_color[j] = "black"}
      else{
        if(stats1$Rank_CI[j] == 1){
          stats1$Rank_CI_color[j] = "blue"}
        else{
          if(stats1$Rank_CI[j] == 2){
            stats1$Rank_CI_color[j] = "lightblue"}
          else{
            if(stats1$Rank_CI[j] == 3){
              stats1$Rank_CI_color[j] = "green"}
            else{
              if(stats1$Rank_CI[j] == 4){
                stats1$Rank_CI_color[j] = "yellowgreen"}
              else{
                if(stats1$Rank_CI[j] == 5){
                  stats1$Rank_CI_color[j] = "yellow"}
                else{
                  if(stats1$Rank_CI[j] == 6){
                    stats1$Rank_CI_color[j] = "orange"}
                  else{
                    if(stats1$Rank_CI[j] == 7){
                      stats1$Rank_CI_color[j] = "red"}}}}}}}}}}
  if(101 - sum(is.na(stats1$Rank_CI)) == 6){
    for(j in 1:101){
      if(is.na(stats1$Rank_CI[j]) == TRUE){
        stats1$Rank_CI_color[j] = "black"}
      else{
        if(stats1$Rank_CI[j] == 1){
          stats1$Rank_CI_color[j] = "lightblue"}
        else{
          if(stats1$Rank_CI[j] == 2){
            stats1$Rank_CI_color[j] = "green"}
          else{
            if(stats1$Rank_CI[j] == 3){
              stats1$Rank_CI_color[j] = "yellowgreen"}
            else{
              if(stats1$Rank_CI[j] == 4){
                stats1$Rank_CI_color[j] = "yellow"}
              else{
                if(stats1$Rank_CI[j] == 5){
                  stats1$Rank_CI_color[j] = "orange"}
                else{
                  if(stats1$Rank_CI[j] == 6){
                    stats1$Rank_CI_color[j] = "red"}}}}}}}}}
  if(101 - sum(is.na(stats1$Rank_CI)) == 5){
    for(j in 1:101){
      if(is.na(stats1$Rank_CI[j]) == TRUE){
        stats1$Rank_CI_color[j] = "black"}
      else{
        if(stats1$Rank_CI[j] == 1){
          stats1$Rank_CI_color[j] = "lightblue"}
        else{
          if(stats1$Rank_CI[j] == 2){
            stats1$Rank_CI_color[j] = "green"}
          else{
            if(stats1$Rank_CI[j] == 3){
              stats1$Rank_CI_color[j] = "yellow"}
            else{
              if(stats1$Rank_CI[j] == 4){
                stats1$Rank_CI_color[j] = "orange"}
              else{
                if(stats1$Rank_CI[j] == 5){
                  stats1$Rank_CI_color[j] = "red"}}}}}}}}
  if(101 - sum(is.na(stats1$Rank_CI)) == 4){
    for(j in 1:101){
      if(is.na(stats1$Rank_CI[j]) == TRUE){
        stats1$Rank_CI_color[j] = "black"}
      else{
        if(stats1$Rank_CI[j] == 1){
          stats1$Rank_CI_color[j] = "green"}
        else{
          if(stats1$Rank_CI[j] == 2){
            stats1$Rank_CI_color[j] = "yellow"}
          else{
            if(stats1$Rank_CI[j] == 3){
              stats1$Rank_CI_color[j] = "orange"}
            else{
              if(stats1$Rank_CI[j] == 4){
                stats1$Rank_CI_color[j] = "red"}}}}}}}
  if(101 - sum(is.na(stats1$Rank_CI)) == 3){
    for(j in 1:101){
      if(is.na(stats1$Rank_CI[j]) == TRUE){
        stats1$Rank_CI_color[j] = "black"}
      else{
        if(stats1$Rank_CI[j] == 1){
          stats1$Rank_CI_color[j] = "green"}
        else{
          if(stats1$Rank_CI[j] == 2){
            stats1$Rank_CI_color[j] = "yellow"}
          else{
            if(stats1$Rank_CI[j] == 3){
              stats1$Rank_CI_color[j] = "red"}}}}}}
  stats2 = stats2%>%
    mutate("Percent Change: Mean" = round(100*(stats2$mean-(stats2$mean[num2]))/(stats2$mean[num2]),4)) %>%
    mutate("Percent Change: SD" = round(100*(stats2$std-(stats2$std[num2]))/(stats2$std[num2]),4))
  stats2 = stats2%>%
    mutate("Mean vs SD Percent Change" = round(stats2$`Percent Change: Mean`/stats2$`Percent Change: SD`,4)) %>%
    mutate("Lower_CI" = stats2$mean - 1.96*stats2$std) %>%
    mutate("Upper_CI" = stats2$mean + 1.96*stats2$std)
  change = vector()
  if(i == 1){
    stats2$Rank_color_std[6:13] = "lightblue"}
  if(i == 2){
    stats2$Rank_color_std[8:17] = "lightblue"}
  if(i == 3){
    stats2$Rank_color_std[11:34] = "lightblue"}
  if(i == 4){
    stats2$Rank_color_std[4:41] = "lightblue"}
  if(i == 5){
    stats2$Rank_color_std[c(15:60, 62:74)] = "lightblue"}
  stats2 = stats2 %>% 
    mutate("Signif" = stats1$Lower_CI[1:101] == max(stats1$Lower_CI)| stats1$Num[1:101] %in% c(0,60,100))
  stats_signif2 = subset(stats2, stats2$Signif == TRUE)
  stats_Not_signif2 = subset(stats2, stats2$Signif != TRUE)
  stats_signif2 = stats_signif2 %>%
    mutate("Rank_CI" = length(stats_signif2$Signif) + 1 - rank(stats_signif2$Lower_CI))
  stats_Not_signif2 = stats_Not_signif2 %>%
    mutate("Rank_CI" = NA)
  stats2 = rbind(stats_Not_signif2, stats_signif2)
  stats2_num = order(stats2$Num)
  stats2 = stats2[c(stats2_num),]
  stats2 = stats2 %>%
    mutate("Rank_CI_color" = NA)
  if(101 - sum(is.na(stats2$Rank_CI)) == 9){
    for(j in 1:101){
      if(is.na(stats2$Rank_CI[j]) == TRUE){
        stats2$Rank_CI_color[j] = "black"}
      else{
        if(stats2$Rank_CI[j] == 1){
          stats2$Rank_CI_color[j] = "blue"}
        else{
          if(stats2$Rank_CI[j] == 2){
            stats2$Rank_CI_color[j] = "lightblue"}
          else{
            if(stats2$Rank_CI[j] == 3){
              stats2$Rank_CI_color[j] = "aquamarine"}
            else{
              if(stats2$Rank_CI[j] == 4){
                stats2$Rank_CI_color[j] = "lightgreen"}
              else{
                if(stats2$Rank_CI[j] == 5){
                  stats2$Rank_CI_color[j] = "green"}
                else{
                  if(stats2$Rank_CI[j] == 6){
                    stats2$Rank_CI_color[j] = "yellowgreen"}
                  else{
                    if(stats2$Rank_CI[j] == 7){
                      stats2$Rank_CI_color[j] = "yellow"}
                    else{
                      if(stats2$Rank_CI[j] == 8){
                        stats2$Rank_CI_color[j] = "orange"}
                      else{
                        if(stats2$Rank_CI[j] == 9){
                          stats2$Rank_CI_color[j] = "red"}}}}}}}}}}}}
  if(101 - sum(is.na(stats2$Rank_CI)) == 8){
    for(j in 1:101){
      if(is.na(stats2$Rank_CI[j]) == TRUE){
        stats2$Rank_CI_color[j] = "black"}
      else{
        if(stats2$Rank_CI[j] == 1){
          stats2$Rank_CI_color[j] = "blue"}
        else{
          if(stats2$Rank_CI[j] == 2){
            stats2$Rank_CI_color[j] = "lightblue"}
          else{
            if(stats2$Rank_CI[j] == 3){
              stats2$Rank_CI_color[j] = "lightgreen"}
            else{
              if(stats2$Rank_CI[j] == 4){
                stats2$Rank_CI_color[j] = "green"}
              else{
                if(stats2$Rank_CI[j] == 5){
                  stats2$Rank_CI_color[j] = "yellowgreen"}
                else{
                  if(stats2$Rank_CI[j] == 6){
                    stats2$Rank_CI_color[j] = "yellow"}
                  else{
                    if(stats2$Rank_CI[j] == 7){
                      stats2$Rank_CI_color[j] = "orange"}
                    else{
                      if(stats2$Rank_CI[j] == 8){
                        stats2$Rank_CI_color[j] = "red"}}}}}}}}}}}
  if(101 - sum(is.na(stats2$Rank_CI)) == 7){
    for(j in 1:101){
      if(is.na(stats2$Rank_CI[j]) == TRUE){
        stats2$Rank_CI_color[j] = "black"}
      else{
        if(stats2$Rank_CI[j] == 1){
          stats2$Rank_CI_color[j] = "blue"}
        else{
          if(stats2$Rank_CI[j] == 2){
            stats2$Rank_CI_color[j] = "lightblue"}
          else{
            if(stats2$Rank_CI[j] == 3){
              stats2$Rank_CI_color[j] = "green"}
            else{
              if(stats2$Rank_CI[j] == 4){
                stats2$Rank_CI_color[j] = "yellowgreen"}
              else{
                if(stats2$Rank_CI[j] == 5){
                  stats2$Rank_CI_color[j] = "yellow"}
                else{
                  if(stats2$Rank_CI[j] == 6){
                    stats2$Rank_CI_color[j] = "orange"}
                  else{
                    if(stats2$Rank_CI[j] == 7){
                      stats2$Rank_CI_color[j] = "red"}}}}}}}}}}
  if(101 - sum(is.na(stats2$Rank_CI)) == 6){
    for(j in 1:101){
      if(is.na(stats2$Rank_CI[j]) == TRUE){
        stats2$Rank_CI_color[j] = "black"}
      else{
        if(stats2$Rank_CI[j] == 1){
          stats2$Rank_CI_color[j] = "lightblue"}
        else{
          if(stats2$Rank_CI[j] == 2){
            stats2$Rank_CI_color[j] = "green"}
          else{
            if(stats2$Rank_CI[j] == 3){
              stats2$Rank_CI_color[j] = "yellowgreen"}
            else{
              if(stats2$Rank_CI[j] == 4){
                stats2$Rank_CI_color[j] = "yellow"}
              else{
                if(stats2$Rank_CI[j] == 5){
                  stats2$Rank_CI_color[j] = "orange"}
                else{
                  if(stats2$Rank_CI[j] == 6){
                    stats2$Rank_CI_color[j] = "red"}}}}}}}}}
  if(101 - sum(is.na(stats2$Rank_CI)) == 5){
    for(j in 1:101){
      if(is.na(stats2$Rank_CI[j]) == TRUE){
        stats2$Rank_CI_color[j] = "black"}
      else{
        if(stats2$Rank_CI[j] == 1){
          stats2$Rank_CI_color[j] = "lightblue"}
        else{
          if(stats2$Rank_CI[j] == 2){
            stats2$Rank_CI_color[j] = "green"}
          else{
            if(stats2$Rank_CI[j] == 3){
              stats2$Rank_CI_color[j] = "yellow"}
            else{
              if(stats2$Rank_CI[j] == 4){
                stats2$Rank_CI_color[j] = "orange"}
              else{
                if(stats2$Rank_CI[j] == 5){
                  stats2$Rank_CI_color[j] = "red"}}}}}}}}
  if(101 - sum(is.na(stats2$Rank_CI)) == 4){
    for(j in 1:101){
      if(is.na(stats2$Rank_CI[j]) == TRUE){
        stats2$Rank_CI_color[j] = "black"}
      else{
        if(stats2$Rank_CI[j] == 1){
          stats2$Rank_CI_color[j] = "green"}
        else{
          if(stats2$Rank_CI[j] == 2){
            stats2$Rank_CI_color[j] = "yellow"}
          else{
            if(stats2$Rank_CI[j] == 3){
              stats2$Rank_CI_color[j] = "orange"}
            else{
              if(stats2$Rank_CI[j] == 4){
                stats2$Rank_CI_color[j] = "red"}}}}}}}
  if(101 - sum(is.na(stats2$Rank_CI)) == 3){
    for(j in 1:101){
      if(is.na(stats2$Rank_CI[j]) == TRUE){
        stats2$Rank_CI_color[j] = "black"}
      else{
        if(stats2$Rank_CI[j] == 1){
          stats2$Rank_CI_color[j] = "green"}
        else{
          if(stats2$Rank_CI[j] == 2){
            stats2$Rank_CI_color[j] = "yellow"}
          else{
            if(stats2$Rank_CI[j] == 3){
              stats2$Rank_CI_color[j] = "red"}}}}}}
  stats = rbind(stats1, stats2)
  assign(paste0(name, "_stats"), stats)
  for(j in 5:7){
    data = frame[,c(1,2,j,9)]
    data = data %>%
      mutate("Type" = colnames(data)[3])
    colnames(data)[3] = "Value"
    min1 = min(data$Value[1:101])
    max1 = max(data$Value[1:101])
    min2 = min(data$Value[102:202])
    max2 = max(data$Value[102:202])
    vect0 = vector()
    vect0 = append(vect0, c(1,61,101))
    for(k in 1:101){
      if(data$Value[[j]] == min1 | data$Value[[k]] == max1){
        vect0 = append(vect0, k)}}
    vect0 = unique(vect0)
    vect0 = sort(vect0)
    vect1 = vector()
    vect1 = append(vect1, c(102,162,202))
    for(k in 102:202){
      if(data$Value[[k]] == min2| data$Value[[k]] == max2){
        vect1 = append(vect1, k)}}
    vect1 = unique(vect1)
    vect1 = sort(vect1)
    vect_sig = vector()
    vect_sig = append(vect_sig, c(vect0,vect1))
    sig_data1 = data[c(vect0),]
    sig_data2 = data[c(vect1),]
    sig_data = data[-c(vect_sig),]
    sig_data <- sig_data %>%
      mutate("Rank_Value" = NA)
    sig_data1 <- sig_data1 %>%
      mutate("Rank_Value" = 1 + length(sig_data1$Value) - rank(sig_data1$Value))
    sig_data2 <- sig_data2 %>%
      mutate("Rank_Value" = 1 + length(sig_data1$Value) - rank(sig_data2$Value))
    sig_data12 = rbind(sig_data1, sig_data2)
    data = rbind(sig_data, sig_data1, sig_data2)
    data_A = subset(data, data$Method == "Arithmetic")
    data_G = subset(data, data$Method == "Geometric")
    data_A_num = order(data_A$Num)
    data_G_num = order(data_G$Num)
    data_A = data_A[c(data_A_num),]
    data_G = data_G[c(data_G_num),]
    data = rbind(data_A, data_G)
    data["Rank_color_Value"] = NA
    for(k in 1:202){
      if(is.na(data$Rank_Value[k]) == TRUE){
        data$Rank_color_Value[k] = "black"}
      else{
        if(data$Rank_Value[k] == 1){
          data$Rank_color_Value[k] = "green"}
        else{
          if(data$Rank_Value[k] == 2){
            data$Rank_color_Value[k] = "yellow"}
          else{
            if(data$Rank_Value[k] == 3){
              data$Rank_color_Value[k] = "orange"}
            else{
              if(data$Rank_Value[k] == 4){
                data$Rank_color_Value[k] = "red"}}}}}}
    if(j==5){
      combo = data}
    else{
      if(j!=5){
        combo = rbind(combo, data)}}
    assign(paste0(name, "_GoF"), combo)}}


 
```


# Monthly Stats
```{r}

Monthly_stats["Allocation1"] = NA
for(i in 1:202){
  if(Monthly_stats$Rank_color_std[i] == "lightblue"){
    Monthly_stats$Allocation1[i] = "Alternatives"}}


if(i == 1){
    stats2$Rank_color_std[6:13] = "lightblue"}
  if(i == 2){
    stats2$Rank_color_std[8:17] = "lightblue"}
  if(i == 3){
    stats2$Rank_color_std[10:34] = "lightblue"}
  if(i == 4){
    stats2$Rank_color_std[4:35] = "lightblue"}
  if(i == 4){
    stats2$Rank_color_std[4:41] = "lightblue"}
  if(i == 5){
    stats2$Rank_color_std[15:66] = "lightblue"}
  if(i == 5){
    stats2$Rank_color_std[15:74] = "lightblue"}


signif_stats_Monthly = subset(Monthly_stats, !(Monthly_stats$Rank_color_std %in% c("black", "lightblue")))
nonsignif_stats_Monthly1 = subset(Monthly_stats, Monthly_stats$Rank_color_std == "black")
nonsignif_stats_Monthly2 = subset(Monthly_stats, Monthly_stats$Rank_color_std == "lightblue")
signif_pts0 = signif_stats_Monthly
signif_pts1 = nonsignif_stats_Monthly1
signif_pts2 = nonsignif_stats_Monthly2
signif_pts0$Allocation = factor(signif_pts0$Allocation, levels = c(unique(signif_pts0$Allocation)))
col_pal <- c(signif_pts0$Rank_color_std)
col_pal2 <- c(signif_pts2$Rank_color_std)
vect = vector()
vect = append(vect, c(col_pal))
length
m1 = ggplot(data = signif_pts1, aes(x = std, y = mean, group = Method)) +
  facet_wrap(~Method, nrow=2, scales = "free") +
  geom_point(aes(x = std, y = mean, fill = Method)) + 
  geom_label(data=signif_pts0[c(2,6),], aes(x = std + 0.013, y = mean + 0.0005, color = Method,
                                   label = paste0("Lowest Risk: ", Num, "/", 100-Num, "\n",
                                     "Mean: ", round(mean, 4), ", ", 
                                     "SD: ", round(std, 4))),
             color = "darkgreen", size=4) +
  geom_label(data=signif_pts2[c(8,16),], aes(x = std + 0.016, y = mean + 0.0008, color = Method,
                                   label = paste0("Alternative Options: ", signif_pts2$Num[1], "/", 100 - signif_pts2$Num[1], " - ", signif_pts2$Num[8], "/", 100 - signif_pts2$Num[8])),
             color = "blue", size=4) +
  geom_point(data = signif_pts2, aes(fill = Allocation1), shape = 21, size = 2.5) +
  geom_point(data = signif_pts0, aes(color=Allocation), size=4) +
  scale_fill_manual(values = col_pal2, limits = "Alternatives") +
  scale_color_manual(values = col_pal) +
  scale_shape_binned()+
  labs(title = "Mean vs Standard Deviation") +
  ylab("Mean") +
  xlab("Standard Deviation") +
  theme(plot.title = element_text(hjust = 0.5, size =15),
        axis.text = element_text(size = 10),
        axis.title = element_text(size=12),
        strip.text = element_text(size=12),
        legend.position = "bottom",
        legend.text = element_text(size=10, vjust = 0.5),
        legend.title = element_blank(),
        legend.box = "vertical",
        legend.margin=unit(0, "cm")) +
  guides(color = guide_legend(nrow = 2, byrow = TRUE, order=2),
         fill = guide_legend(order=1))

Monthly_stats$Allocation = factor(Monthly_stats$Allocation, levels = c(unique(Monthly_stats$Allocation)))

signif1 = subset(Monthly_stats, Monthly_stats$Rank_CI_color != "black")
signif2 = subset(Monthly_stats, Monthly_stats$Rank_CI_color == "black")


m2 = ggplot(data = signif2, aes(x = Num, y = Lower_CI, xend = Num, yend = Upper_CI)) + 
  geom_segment() + 
  geom_segment(data = signif1, aes(colour = Allocation), size = 1.5) + ylab("95% CI") + xlab("Asset Allocation") + 
  facet_wrap(~Method, nrow=2) + 
  scale_color_manual(values = signif1$Rank_CI_color) + 
  labs(title = "95% Confidence Interval") + 
  geom_label(data=signif1[c(2,6),], aes(x = Num + 12, y = Lower_CI - 0.05, color = Method, label = paste0(
    "Largest Lower Bound: ", Num, "/", 100-Num, "\n","95% CI: ", round(Lower_CI,4))), color = "darkgreen", size=4) +
  theme(plot.title = element_text(hjust = 0.5, size =15),
        axis.text = element_text(size = 10),
        axis.title = element_text(size=12),
        strip.text = element_text(size=12),
        legend.position = "bottom",
        legend.text = element_text(size=10, vjust = 0.5),
        legend.title = element_blank()) +
  guides(color = guide_legend(nrow = 2, byrow = TRUE), fill = "none")



grid.arrange(m1,m2, ncol=2, top=text_grob("Monthly Returns", size = 18, face = "bold"))

```

# Monthly GoF
```{r}

signif_GoF_Monthly = subset(Monthly_GoF, Monthly_GoF$Rank_color_Value != "black" & Monthly_GoF$Type == "rrr")
nonsignif_GoF_Monthly1 = subset(Monthly_GoF, Monthly_GoF$Rank_color_Value == "black" & Monthly_GoF$Type == "rrr")
signif_pts0 = signif_GoF_Monthly
signif_pts1 = nonsignif_GoF_Monthly1
signif_pts0$Allocation = factor(signif_pts0$Allocation, levels = c(unique(signif_pts0$Allocation)))
col_pal <- c(signif_pts0$Rank_color_Value)

mr1 = ggplot(data = signif_pts1, aes(x = Num, y = Value, group = Method)) +
  facet_wrap(~Method, nrow=2, scales = "free") +
  geom_point(aes(x = Num, y = Value, fill = Method)) + 
  geom_label(data=signif_pts0[c(2,6),], aes(x = Num+20, y = Value-.03, color = Method,
                                   label = paste0("Largest Ratio: ", Num, "/", 100-Num, "\n",
                                    "Risk Reward Ratio = ", round(Value, 4))),
             color = "darkgreen", size=4) +
  geom_point(data = signif_pts0, aes(color=Allocation), size=4) +
  scale_color_manual(values = col_pal) +
  labs(title = "Risk Reward Ratio") +
  ylab("Ratio") +
  xlab("Allocation (Large Cap)") +
  theme(plot.title = element_text(hjust = 0.5, size =15),
        axis.text = element_text(size = 10),
        axis.title = element_text(size=12),
        strip.text = element_text(size=12),
        legend.position = "bottom",
        legend.text = element_text(size=10, vjust = 0.5),
        legend.title = element_blank(),
        legend.box = "vertical",
        legend.margin=unit(0, "cm")) +
  guides(color = guide_legend(nrow = 4, byrow = TRUE, order=2),
         fill = "none")

signif_GoF_Monthly = subset(Monthly_GoF, Monthly_GoF$Rank_color_Value != "black" & Monthly_GoF$Type == "sharpe1")
nonsignif_GoF_Monthly1 = subset(Monthly_GoF, Monthly_GoF$Rank_color_Value == "black" & Monthly_GoF$Type == "sharpe1")
signif_pts0 = signif_GoF_Monthly
signif_pts1 = nonsignif_GoF_Monthly1
signif_pts0$Allocation = factor(signif_pts0$Allocation, levels = c(unique(signif_pts0$Allocation)))
col_pal <- c(signif_pts0$Rank_color_Value)

mr2 = ggplot(data = signif_pts1, aes(x = Num, y = Value, group = Method)) +
  facet_wrap(~Method, nrow=2, scales = "free") +
  geom_point(aes(x = Num, y = Value, fill = Method)) + 
  geom_label(data=signif_pts0[c(2,6),], aes(x = Num+20, y = Value-.03, color = Method,
                                   label = paste0("Largest Ratio: ", Num, "/", 100-Num, "\n",
                                    "Sharpe Ratio = ", round(Value, 4))),
             color = "darkgreen", size=4) +
  geom_point(data = signif_pts0, aes(color=Allocation), size=4) +
  scale_color_manual(values = c("yellow", "green", "orange", "red", "green")) +
  labs(title = "Sharpe Ratio 1") +
  ylab("Ratio") +
  xlab("Allocation (Large Cap)") +
  theme(plot.title = element_text(hjust = 0.5, size =15),
        axis.text = element_text(size = 10),
        axis.title = element_text(size=12),
        strip.text = element_text(size=12),
        legend.position = "bottom",
        legend.text = element_text(size=10, vjust = 0.5),
        legend.title = element_blank(),
        legend.box = "vertical",
        legend.margin=unit(0, "cm")) +
  guides(color = guide_legend(nrow = 5, byrow = TRUE, order=2),
         fill = "none")


signif_GoF_Monthly = subset(Monthly_GoF, Monthly_GoF$Rank_color_Value != "black" & Monthly_GoF$Type == "sharpe2")
nonsignif_GoF_Monthly1 = subset(Monthly_GoF, Monthly_GoF$Rank_color_Value == "black" & Monthly_GoF$Type == "sharpe2")
signif_pts0 = signif_GoF_Monthly
signif_pts1 = nonsignif_GoF_Monthly1
signif_pts0$Allocation = factor(signif_pts0$Allocation, levels = c(unique(signif_pts0$Allocation)))
col_pal <- c(signif_pts0$Rank_color_Value)
mr3 = ggplot(data = signif_pts1, aes(x = Num, y = Value, group = Method)) +
  facet_wrap(~Method, nrow=2, scales = "free") +
  geom_point(aes(x = Num, y = Value, fill = Method)) + 
  geom_label(data=signif_pts0[c(2,6),], aes(x = Num+20, y = Value-.03, color = Method,
                                   label = paste0("Largest Ratio: ", Num, "/", 100-Num, "\n",
                                    "Sharpe Ratio = ", round(Value, 4))),
             color = "darkgreen", size=4) +
  geom_point(data = signif_pts0, aes(color=Allocation), size=4) +
  scale_color_manual(values = col_pal) +
  labs(title = "Sharpe Ratio 2") +
  ylab("Ratio") +
  xlab("Allocation (Large Cap)") +
  theme(plot.title = element_text(hjust = 0.5, size =15),
        axis.text = element_text(size = 10),
        axis.title = element_text(size=12),
        strip.text = element_text(size=12),
        legend.position = "bottom",
        legend.text = element_text(size=10, vjust = 0.5),
        legend.title = element_blank(),
        legend.box = "vertical",
        legend.margin=unit(0, "cm")) +
  guides(color = guide_legend(nrow = 4, byrow = TRUE, order=2),
         fill = "none")

grid.arrange(mr1,mr2,mr3, ncol=3, top=text_grob("Monthly Returns", size = 18, face = "bold"))
```
# Yearly Stats
```{r}
Yearly_stats["Allocation1"] = NA
for(i in 1:202){
  if(Yearly_stats$Rank_color_std[i] == "lightblue"){
    Yearly_stats$Allocation1[i] = "Alternatives"}}


if(i == 1){
    stats2$Rank_color_std[6:13] = "lightblue"}
  if(i == 2){
    stats2$Rank_color_std[8:17] = "lightblue"}
  if(i == 3){
    stats2$Rank_color_std[10:34] = "lightblue"}
  if(i == 4){
    stats2$Rank_color_std[4:35] = "lightblue"}
  if(i == 4){
    stats2$Rank_color_std[4:41] = "lightblue"}
  if(i == 5){
    stats2$Rank_color_std[15:66] = "lightblue"}
  if(i == 5){
    stats2$Rank_color_std[15:74] = "lightblue"}


signif_stats_Yearly = subset(Yearly_stats, !(Yearly_stats$Rank_color_std %in% c("black", "lightblue")))
nonsignif_stats_Yearly1 = subset(Yearly_stats, Yearly_stats$Rank_color_std == "black")
nonsignif_stats_Yearly2 = subset(Yearly_stats, Yearly_stats$Rank_color_std == "lightblue")
signif_pts0 = signif_stats_Yearly
signif_pts1 = nonsignif_stats_Yearly1
signif_pts2 = nonsignif_stats_Yearly2
signif_pts0$Allocation = factor(signif_pts0$Allocation, levels = c(unique(signif_pts0$Allocation)))
col_pal <- c(signif_pts0$Rank_color_std)
col_pal2 <- c(signif_pts2$Rank_color_std)
vect = vector()
vect = append(vect, c(col_pal))
length
y1 = ggplot(data = signif_pts1, aes(x = std, y = mean, group = Method)) +
  facet_wrap(~Method, nrow=2, scales = "free") +
  geom_point(aes(x = std, y = mean, fill = Method)) + 
  geom_label(data=signif_pts0[c(2,6),], aes(x = std + 0.06, y = mean + 0.005, color = Method,
                                   label = paste0("Lowest Risk: ", Num, "/", 100-Num, "\n",
                                     "Mean: ", round(mean, 4), ", ", 
                                     "SD: ", round(std, 4))),
             color = "darkgreen", size=4) +
  geom_label(data=signif_pts2[c(10,20),], aes(x = std + 0.06, y = mean + 0.008, color = Method,
                                   label = paste0("Alternative Options: ", signif_pts2$Num[1], "/", 100 - signif_pts2$Num[1], " - ", signif_pts2$Num[10], "/", 100 - signif_pts2$Num[10])),
             color = "blue", size=4) +
  geom_point(data = signif_pts2, aes(fill = Allocation1), shape = 21, size = 2.5) +
  geom_point(data = signif_pts0, aes(color=Allocation), size=4) +
  scale_fill_manual(values = col_pal2, limits = "Alternatives") +
  scale_color_manual(values = col_pal) +
  scale_shape_binned()+
  labs(title = "Mean vs Standard Deviation") +
  ylab("Mean") +
  xlab("Standard Deviation") +
  theme(plot.title = element_text(hjust = 0.5, size =15),
        axis.text = element_text(size = 10),
        axis.title = element_text(size=12),
        strip.text = element_text(size=12),
        legend.position = "bottom",
        legend.text = element_text(size=10, vjust = 0.5),
        legend.title = element_blank(),
        legend.box = "vertical",
        legend.margin=unit(0, "cm")) +
  guides(color = guide_legend(nrow = 2, byrow = TRUE, order=2),
         fill = guide_legend(order=1))

Yearly_stats$Allocation = factor(Yearly_stats$Allocation, levels = c(unique(Yearly_stats$Allocation)))

signif1 = subset(Yearly_stats, Yearly_stats$Rank_CI_color != "black")
signif2 = subset(Yearly_stats, Yearly_stats$Rank_CI_color == "black")


y2 = ggplot(data = signif2, aes(x = Num, y = Lower_CI, xend = Num, yend = Upper_CI)) + 
  geom_segment() + 
  geom_segment(data = signif1, aes(colour = Allocation), size = 1.5) + ylab("95% CI") + xlab("Asset Allocation") + 
  facet_wrap(~Method, nrow=2) + 
  scale_color_manual(values = signif1$Rank_CI_color) + 
  labs(title = "95% Confidence Interval") + 
  geom_label(data=signif1[c(2,6),], aes(x = Num + 12, y = Lower_CI - 0.17, color = Method, label = paste0(
    "Largest Lower Bound: ", Num, "/", 100-Num, "\n","95% CI: ", round(Lower_CI,4))), color = "darkgreen", size=4) +
  theme(plot.title = element_text(hjust = 0.5, size =15),
        axis.text = element_text(size = 10),
        axis.title = element_text(size=12),
        strip.text = element_text(size=12),
        legend.position = "bottom",
        legend.text = element_text(size=10, vjust = 0.5),
        legend.title = element_blank()) +
  guides(color = guide_legend(nrow = 2, byrow = TRUE), fill = "none")



grid.arrange(y1,y2, ncol=2, top=text_grob("12 Month Returns", size = 18, face = "bold"))

```
# Yearly GoF
```{r}

signif_GoF_Yearly = subset(Yearly_GoF, Yearly_GoF$Rank_color_Value != "black" & Yearly_GoF$Type == "rrr")
nonsignif_GoF_Yearly1 = subset(Yearly_GoF, Yearly_GoF$Rank_color_Value == "black" & Yearly_GoF$Type == "rrr")
signif_pts0 = signif_GoF_Yearly
signif_pts1 = nonsignif_GoF_Yearly1
signif_pts0$Allocation = factor(signif_pts0$Allocation, levels = c(unique(signif_pts0$Allocation)))
col_pal <- c(signif_pts0$Rank_color_Value)

yr1 = ggplot(data = signif_pts1, aes(x = Num, y = Value, group = Method)) +
  facet_wrap(~Method, nrow=2, scales = "free") +
  geom_point(aes(x = Num, y = Value, fill = Method)) + 
  geom_label(data=signif_pts0[c(2,6),], aes(x = Num+20, y = Value-.03, color = Method,
                                   label = paste0("Largest Ratio: ", Num, "/", 100-Num, "\n",
                                    "Risk Reward Ratio = ", round(Value, 4))),
             color = "darkgreen", size=4) +
  geom_point(data = signif_pts0, aes(color=Allocation), size=4) +
  scale_color_manual(values = col_pal) +
  labs(title = "Risk Reward Ratio") +
  ylab("Ratio") +
  xlab("Allocation (Large Cap)") +
  theme(plot.title = element_text(hjust = 0.5, size =15),
        axis.text = element_text(size = 10),
        axis.title = element_text(size=12),
        strip.text = element_text(size=12),
        legend.position = "bottom",
        legend.text = element_text(size=10, vjust = 0.5),
        legend.title = element_blank(),
        legend.box = "vertical",
        legend.margin=unit(0, "cm")) +
  guides(color = guide_legend(nrow = 4, byrow = TRUE, order=2),
         fill = "none")

signif_GoF_Yearly = subset(Yearly_GoF, Yearly_GoF$Rank_color_Value != "black" & Yearly_GoF$Type == "sharpe1")
nonsignif_GoF_Yearly1 = subset(Yearly_GoF, Yearly_GoF$Rank_color_Value == "black" & Yearly_GoF$Type == "sharpe1")
signif_pts0 = signif_GoF_Yearly
signif_pts1 = nonsignif_GoF_Yearly1
signif_pts0$Allocation = factor(signif_pts0$Allocation, levels = c(unique(signif_pts0$Allocation)))
col_pal <- c(signif_pts0$Rank_color_Value)

yr2 = ggplot(data = signif_pts1, aes(x = Num, y = Value, group = Method)) +
  facet_wrap(~Method, nrow=2, scales = "free") +
  geom_point(aes(x = Num, y = Value, fill = Method)) + 
  geom_label(data=signif_pts0[c(2,6),], aes(x = Num+20, y = Value-.03, color = Method,
                                   label = paste0("Largest Ratio: ", Num, "/", 100-Num, "\n",
                                    "Sharpe Ratio = ", round(Value, 4))),
             color = "darkgreen", size=4) +
  geom_point(data = signif_pts0, aes(color=Allocation), size=4) +
  scale_color_manual(values = c("yellow", "green", "orange", "red", "green")) +
  labs(title = "Sharpe Ratio 1") +
  ylab("Ratio") +
  xlab("Allocation (Large Cap)") +
  theme(plot.title = element_text(hjust = 0.5, size =15),
        axis.text = element_text(size = 10),
        axis.title = element_text(size=12),
        strip.text = element_text(size=12),
        legend.position = "bottom",
        legend.text = element_text(size=10, vjust = 0.5),
        legend.title = element_blank(),
        legend.box = "vertical",
        legend.margin=unit(0, "cm")) +
  guides(color = guide_legend(nrow = 5, byrow = TRUE, order=2),
         fill = "none")


signif_GoF_Yearly = subset(Yearly_GoF, Yearly_GoF$Rank_color_Value != "black" & Yearly_GoF$Type == "sharpe2")
nonsignif_GoF_Yearly1 = subset(Yearly_GoF, Yearly_GoF$Rank_color_Value == "black" & Yearly_GoF$Type == "sharpe2")
signif_pts0 = signif_GoF_Yearly
signif_pts1 = nonsignif_GoF_Yearly1
signif_pts0$Allocation = factor(signif_pts0$Allocation, levels = c(unique(signif_pts0$Allocation)))
col_pal <- c(signif_pts0$Rank_color_Value)
yr3 = ggplot(data = signif_pts1, aes(x = Num, y = Value, group = Method)) +
  facet_wrap(~Method, nrow=2, scales = "free") +
  geom_point(aes(x = Num, y = Value, fill = Method)) + 
  geom_label(data=signif_pts0[c(2,6),], aes(x = Num+20, y = Value-.03, color = Method,
                                   label = paste0("Largest Ratio: ", Num, "/", 100-Num, "\n",
                                    "Sharpe Ratio = ", round(Value, 4))),
             color = "darkgreen", size=4) +
  geom_point(data = signif_pts0, aes(color=Allocation), size=4) +
  scale_color_manual(values = c("yellow", "green", "orange", "red", "green")) +
  labs(title = "Sharpe Ratio 2") +
  ylab("Ratio") +
  xlab("Allocation (Large Cap)") +
  theme(plot.title = element_text(hjust = 0.5, size =15),
        axis.text = element_text(size = 10),
        axis.title = element_text(size=12),
        strip.text = element_text(size=12),
        legend.position = "bottom",
        legend.text = element_text(size=10, vjust = 0.5),
        legend.title = element_blank(),
        legend.box = "vertical",
        legend.margin=unit(0, "cm")) +
  guides(color = guide_legend(nrow = 4, byrow = TRUE, order=2),
         fill = "none")




grid.arrange(yr1,yr2,yr3, ncol=3, top=text_grob("12 Month Returns", size = 18, face = "bold"))

```

# Yearly_10 Stats
```{r}

Yearly_10_stats["Allocation1"] = NA
for(i in 1:202){
  if(Yearly_10_stats$Rank_color_std[i] == "lightblue"){
    Yearly_10_stats$Allocation1[i] = "Alternatives"}}


if(i == 1){
    stats2$Rank_color_std[6:13] = "lightblue"}
  if(i == 2){
    stats2$Rank_color_std[8:17] = "lightblue"}
  if(i == 3){
    stats2$Rank_color_std[10:34] = "lightblue"}
  if(i == 4){
    stats2$Rank_color_std[4:35] = "lightblue"}
  if(i == 4){
    stats2$Rank_color_std[4:41] = "lightblue"}
  if(i == 5){
    stats2$Rank_color_std[15:66] = "lightblue"}
  if(i == 5){
    stats2$Rank_color_std[15:74] = "lightblue"}


signif_stats_Yearly_10 = subset(Yearly_10_stats, !(Yearly_10_stats$Rank_color_std %in% c("black", "lightblue")))
nonsignif_stats_Yearly_101 = subset(Yearly_10_stats, Yearly_10_stats$Rank_color_std == "black")
nonsignif_stats_Yearly_102 = subset(Yearly_10_stats, Yearly_10_stats$Rank_color_std == "lightblue")
signif_pts0 = signif_stats_Yearly_10
signif_pts1 = nonsignif_stats_Yearly_101
signif_pts2 = nonsignif_stats_Yearly_102
signif_pts0$Allocation = factor(signif_pts0$Allocation, levels = c(unique(signif_pts0$Allocation)))
col_pal <- c(signif_pts0$Rank_color_std)
col_pal2 <- c(signif_pts2$Rank_color_std)
vect = vector()
vect = append(vect, c(col_pal))
length
y110 = ggplot(data = signif_pts1, aes(x = std, y = mean, group = Method)) +
  facet_wrap(~Method, nrow=2, scales = "free") +
  geom_point(aes(x = std, y = mean, fill = Method)) + 
  geom_label(data=signif_pts0[c(2,6),], aes(x = std + 0.22, y = mean + 0.005, color = Method,
                                   label = paste0("Lowest Risk: ", Num, "/", 100-Num, "\n",
                                     "Mean: ", round(mean, 4), ", ", 
                                     "SD: ", round(std, 4))),
             color = "darkgreen", size=4) +
  geom_label(data=signif_pts2[c(24,48),], aes(x = std + 0.2, y = mean - 0.1, color = Method,
                                   label = paste0("Alternative Options: ", signif_pts2$Num[1], "/", 100 - signif_pts2$Num[1], " - ", signif_pts2$Num[24], "/", 100 - signif_pts2$Num[24])),
             color = "blue", size=4) +
  geom_point(data = signif_pts2, aes(fill = Allocation1), shape = 21, size = 2.5) +
  geom_point(data = signif_pts0, aes(color=Allocation), size=4) +
  scale_fill_manual(values = col_pal2, limits = "Alternatives") +
  scale_color_manual(values = col_pal) +
  scale_shape_binned()+
  labs(title = "Mean vs Standard Deviation") +
  ylab("Mean") +
  xlab("Standard Deviation") +
  theme(plot.title = element_text(hjust = 0.5, size =15),
        axis.text = element_text(size = 10),
        axis.title = element_text(size=12),
        strip.text = element_text(size=12),
        legend.position = "bottom",
        legend.text = element_text(size=10, vjust = 0.5),
        legend.title = element_blank(),
        legend.box = "vertical",
        legend.margin=unit(0, "cm")) +
  guides(color = guide_legend(nrow = 2, byrow = TRUE, order=2),
         fill = guide_legend(order=1))

Yearly_10_stats$Allocation = factor(Yearly_10_stats$Allocation, levels = c(unique(Yearly_10_stats$Allocation)))

signif1 = subset(Yearly_10_stats, Yearly_10_stats$Rank_CI_color != "black")
signif2 = subset(Yearly_10_stats, Yearly_10_stats$Rank_CI_color == "black")
vect = vector()

y210 = ggplot(data = signif2, aes(x = Num, y = Lower_CI, xend = Num, yend = Upper_CI)) + 
  geom_segment() + 
  geom_segment(data = signif1, aes(colour = Allocation), size = 1.5) + ylab("95% CI") + xlab("Asset Allocation") + 
  facet_wrap(~Method, nrow=2) + 
  scale_color_manual(values = signif1$Rank_CI_color) + 
  labs(title = "95% Confidence Interval") + 
  geom_label(data=signif1[c(2,6),], aes(x = Num, y = Lower_CI - 0.57, color = Method, label = paste0(
    "Largest Lower Bound: ", Num, "/", 100-Num, "\n","95% CI: ", round(Lower_CI,4))), color = "darkgreen", size=4) +
  theme(plot.title = element_text(hjust = 0.5, size =15),
        axis.text = element_text(size = 10),
        axis.title = element_text(size=12),
        strip.text = element_text(size=12),
        legend.position = "bottom",
        legend.text = element_text(size=10, vjust = 0.5),
        legend.title = element_blank()) +
  guides(color = guide_legend(nrow = 2, byrow = TRUE), fill = "none")



grid.arrange(y110,y210, ncol=2, top=text_grob("120 Month Returns", size = 18, face = "bold"))

```

# Yearly_10 GoF
```{r}

signif_GoF_Yearly_10 = subset(Yearly_10_GoF, Yearly_10_GoF$Rank_color_Value != "black" & Yearly_10_GoF$Type == "rrr")
nonsignif_GoF_Yearly_101 = subset(Yearly_10_GoF, Yearly_10_GoF$Rank_color_Value == "black" & Yearly_10_GoF$Type == "rrr")
signif_pts0 = signif_GoF_Yearly_10
signif_pts1 = nonsignif_GoF_Yearly_101
signif_pts0$Allocation = factor(signif_pts0$Allocation, levels = c(unique(signif_pts0$Allocation)))
if(signif_pts0$Allocation[1] == signif_pts0$Allocation[5] | 
   signif_pts0$Allocation[3] == signif_pts0$Allocation[7] | 
   signif_pts0$Allocation[4] == signif_pts0$Allocation[8]){
  if(signif_pts0$Rank_Value[1] != signif_pts0$Rank_Value[5]){
    levels(signif_pts0$Allocation) <- c(levels(signif_pts0$Allocation),
                                        c(paste0(signif_pts0$Allocation[1], 
                                                 " - (", signif_pts0$Method[1],")"),
                                          paste0(signif_pts0$Allocation[5], " - (",
                                                 signif_pts0$Method[5],")")))
    signif_pts0$Allocation[1] = paste0(signif_pts0$Allocation[1], " - (Arithmetic)")
    signif_pts0$Allocation[5] = paste0(signif_pts0$Allocation[5], " - (Geometric)")}
  if(signif_pts0$Rank_Value[3] != signif_pts0$Rank_Value[7]){
    levels(signif_pts0$Allocation) <- c(levels(signif_pts0$Allocation),
                                        c(paste0(signif_pts0$Allocation[3], 
                                                 " - (", signif_pts0$Method[3],")"),
                                          paste0(signif_pts0$Allocation[7], " - (",
                                                 signif_pts0$Method[7],")")))
    signif_pts0$Allocation[3] = paste0(signif_pts0$Allocation[3], " - (Arithmetic)")
    signif_pts0$Allocation[7] = paste0(signif_pts0$Allocation[7], " - (Geometric)")}
  if(signif_pts0$Rank_Value[4] != signif_pts0$Rank_Value[8]){
    levels(signif_pts0$Allocation) <- c(levels(signif_pts0$Allocation),
                                        c(paste0(signif_pts0$Allocation[4], 
                                                 " - (", signif_pts0$Method[4],")"),
                                          paste0(signif_pts0$Allocation[8], " - (",
                                                 signif_pts0$Method[8],")")))
    signif_pts0$Allocation[4] = paste0(signif_pts0$Allocation[4], " - (Arithmetic)")
    signif_pts0$Allocation[8] = paste0(signif_pts0$Allocation[8], " - (Geometric)")}}
signif_pts0$Allocation = factor(signif_pts0$Allocation, levels = c(unique(signif_pts0$Allocation)))
col_pal <- c(signif_pts0$Rank_color_Value)

yr110 = ggplot(data = signif_pts1, aes(x = Num, y = Value, group = Method)) +
  facet_wrap(~Method, nrow=2, scales = "free") +
  geom_point(aes(x = Num, y = Value, fill = Method)) + 
  geom_label(data=signif_pts0[c(2,6),], aes(x = Num+20, y = Value-.4, color = Method,
                                   label = paste0("Largest Ratio: ", Num, "/", 100-Num, "\n",
                                    "Risk Reward Ratio = ", round(Value, 4))),
             color = "darkgreen", size=4) +
  
  geom_point(data = signif_pts0, aes(color=Allocation), size=4) +
  scale_color_manual(values = c("red", "green", "yellow", "orange", "orange","green", "red", "red")) +
  labs(title = "Risk Reward Ratio") +
  ylab("Ratio") +
  xlab("Asset Allocation") +
  theme(plot.title = element_text(hjust = 0.5, size =15),
        axis.text = element_text(size = 10),
        axis.title = element_text(size=12),
        strip.text = element_text(size=12),
        legend.position = "bottom",
        legend.text = element_text(size=10, vjust = 0.5),
        legend.title = element_blank(),
        legend.box = "vertical",
        legend.margin=unit(0, "cm")) +
  guides(color = guide_legend(nrow = 7, byrow = TRUE, order=2),
         fill = "none")



signif_GoF_Yearly_10 = subset(Yearly_10_GoF, Yearly_10_GoF$Rank_color_Value != "black" & Yearly_10_GoF$Type == "sharpe1")
nonsignif_GoF_Yearly_101 = subset(Yearly_10_GoF, Yearly_10_GoF$Rank_color_Value == "black" & Yearly_10_GoF$Type == "sharpe1")
signif_pts0 = signif_GoF_Yearly_10
signif_pts1 = nonsignif_GoF_Yearly_101
signif_pts0$Allocation = factor(signif_pts0$Allocation, levels = c(unique(signif_pts0$Allocation)))
if(signif_pts0$Allocation[1] == signif_pts0$Allocation[5] | 
   signif_pts0$Allocation[3] == signif_pts0$Allocation[7] | 
   signif_pts0$Allocation[4] == signif_pts0$Allocation[8]){
  if(signif_pts0$Rank_Value[1] != signif_pts0$Rank_Value[5]){
    levels(signif_pts0$Allocation) <- c(levels(signif_pts0$Allocation),
                                        c(paste0(signif_pts0$Allocation[1], 
                                                 " - (", signif_pts0$Method[1],")"),
                                          paste0(signif_pts0$Allocation[5], " - (",
                                                 signif_pts0$Method[5],")")))
    signif_pts0$Allocation[1] = paste0(signif_pts0$Allocation[1], " - (Arithmetic)")
    signif_pts0$Allocation[5] = paste0(signif_pts0$Allocation[5], " - (Geometric)")}
  if(signif_pts0$Rank_Value[3] != signif_pts0$Rank_Value[7]){
    levels(signif_pts0$Allocation) <- c(levels(signif_pts0$Allocation),
                                        c(paste0(signif_pts0$Allocation[3], 
                                                 " - (", signif_pts0$Method[3],")"),
                                          paste0(signif_pts0$Allocation[7], " - (",
                                                 signif_pts0$Method[7],")")))
    signif_pts0$Allocation[3] = paste0(signif_pts0$Allocation[3], " - (Arithmetic)")
    signif_pts0$Allocation[7] = paste0(signif_pts0$Allocation[7], " - (Geometric)")}
  if(signif_pts0$Rank_Value[4] != signif_pts0$Rank_Value[8]){
    levels(signif_pts0$Allocation) <- c(levels(signif_pts0$Allocation),
                                        c(paste0(signif_pts0$Allocation[4], 
                                                 " - (", signif_pts0$Method[4],")"),
                                          paste0(signif_pts0$Allocation[8], " - (",
                                                 signif_pts0$Method[8],")")))
    signif_pts0$Allocation[4] = paste0(signif_pts0$Allocation[4], " - (Arithmetic)")
    signif_pts0$Allocation[8] = paste0(signif_pts0$Allocation[8], " - (Geometric)")}}
signif_pts0$Allocation = factor(signif_pts0$Allocation, levels = c(unique(signif_pts0$Allocation)))
col_pal <- c(signif_pts0$Rank_color_Value)

yr210 = ggplot(data = signif_pts1, aes(x = Num, y = Value, group = Method)) +
  facet_wrap(~Method, nrow=2, scales = "free") +
  geom_point(aes(x = Num, y = Value, fill = Method)) + 
  geom_label(data=signif_pts0[c(2,6),], aes(x = Num+20, y = Value-.4, color = Method,
                                   label = paste0("Largest Ratio: ", Num, "/", 100-Num, "\n",
                                    "Sharpe Ratio = ", round(Value, 4))),
             color = "darkgreen", size=4) +
  geom_point(data = signif_pts0, aes(color=Allocation), size=4) +
  scale_color_manual(values = c("red", "green", "yellow", "orange", "orange","green", "red", "red")) +  labs(title = "Sharpe Ratio 1") +
  ylab("Ratio") +
  xlab("Asset Allocation") +
  theme(plot.title = element_text(hjust = 0.5, size =15),
        axis.text = element_text(size = 10),
        axis.title = element_text(size=12),
        strip.text = element_text(size=12),
        legend.position = "bottom",
        legend.text = element_text(size=10, vjust = 0.5),
        legend.title = element_blank(),
        legend.box = "vertical",
        legend.margin=unit(0, "cm")) +
  guides(color = guide_legend(nrow = 7, byrow = TRUE, order=2),
         fill = "none")


signif_GoF_Yearly_10 = subset(Yearly_10_GoF, Yearly_10_GoF$Rank_color_Value != "black" & Yearly_10_GoF$Type == "sharpe2")
nonsignif_GoF_Yearly_101 = subset(Yearly_10_GoF, Yearly_10_GoF$Rank_color_Value == "black" & Yearly_10_GoF$Type == "sharpe2")
signif_pts0 = signif_GoF_Yearly_10
signif_pts1 = nonsignif_GoF_Yearly_101
signif_pts0$Allocation = factor(signif_pts0$Allocation, levels = c(unique(signif_pts0$Allocation)))
if(signif_pts0$Allocation[1] == signif_pts0$Allocation[5] | 
   signif_pts0$Allocation[3] == signif_pts0$Allocation[7] | 
   signif_pts0$Allocation[4] == signif_pts0$Allocation[8]){
  if(signif_pts0$Rank_Value[1] != signif_pts0$Rank_Value[5]){
    levels(signif_pts0$Allocation) <- c(levels(signif_pts0$Allocation),
                                        c(paste0(signif_pts0$Allocation[1], 
                                                 " - (", signif_pts0$Method[1],")"),
                                          paste0(signif_pts0$Allocation[5], " - (",
                                                 signif_pts0$Method[5],")")))
    signif_pts0$Allocation[1] = paste0(signif_pts0$Allocation[1], " - (Arithmetic)")
    signif_pts0$Allocation[5] = paste0(signif_pts0$Allocation[5], " - (Geometric)")}
  if(signif_pts0$Rank_Value[3] != signif_pts0$Rank_Value[7]){
    levels(signif_pts0$Allocation) <- c(levels(signif_pts0$Allocation),
                                        c(paste0(signif_pts0$Allocation[3], 
                                                 " - (", signif_pts0$Method[3],")"),
                                          paste0(signif_pts0$Allocation[7], " - (",
                                                 signif_pts0$Method[7],")")))
    signif_pts0$Allocation[3] = paste0(signif_pts0$Allocation[3], " - (Arithmetic)")
    signif_pts0$Allocation[7] = paste0(signif_pts0$Allocation[7], " - (Geometric)")}
  if(signif_pts0$Rank_Value[4] != signif_pts0$Rank_Value[8]){
    levels(signif_pts0$Allocation) <- c(levels(signif_pts0$Allocation),
                                        c(paste0(signif_pts0$Allocation[4], 
                                                 " - (", signif_pts0$Method[4],")"),
                                          paste0(signif_pts0$Allocation[8], " - (",
                                                 signif_pts0$Method[8],")")))
    signif_pts0$Allocation[4] = paste0(signif_pts0$Allocation[4], " - (Arithmetic)")
    signif_pts0$Allocation[8] = paste0(signif_pts0$Allocation[8], " - (Geometric)")}}
signif_pts0$Allocation = factor(signif_pts0$Allocation, levels = c(unique(signif_pts0$Allocation)))
col_pal <- c(signif_pts0$Rank_color_Value)
yr310 = ggplot(data = signif_pts1, aes(x = Num, y = Value, group = Method)) +
  facet_wrap(~Method, nrow=2, scales = "free") +
  geom_point(aes(x = Num, y = Value, fill = Method)) + 
  geom_label(data=signif_pts0[c(2,6),], aes(x = Num+20, y = Value-.4, color = Method,
                                   label = paste0("Largest Ratio: ", Num, "/", 100-Num, "\n",
                                    "Sharpe Ratio = ", round(Value, 4))),
             color = "darkgreen", size=4) +
  geom_point(data = signif_pts0, aes(color=Allocation), size=4) +
  scale_color_manual(values = c("red", "green", "yellow", "orange", "orange","green", "red", "red")) +  labs(title = "Sharpe Ratio 2") +
  ylab("Ratio") +
  xlab("Asset Allocation") +
  theme(plot.title = element_text(hjust = 0.5, size =15),
        axis.text = element_text(size = 10),
        axis.title = element_text(size=12),
        strip.text = element_text(size=12),
        legend.position = "bottom",
        legend.text = element_text(size=10, vjust = 0.5),
        legend.title = element_blank(),
        legend.box = "vertical",
        legend.margin=unit(0, "cm")) +
  guides(color = guide_legend(nrow = 7, byrow = TRUE, order=2),
         fill = "none")

grid.arrange(yr110,yr210,yr310, ncol=3, top=text_grob("120 Month Returns", size = 18, face = "bold"))

```

# Yearly_20 Stats
```{r}

Yearly_20_stats["Allocation1"] = NA
for(i in 1:202){
  if(Yearly_20_stats$Rank_color_std[i] == "lightblue"){
    Yearly_20_stats$Allocation1[i] = "Alternatives"}}


if(i == 1){
    stats2$Rank_color_std[6:13] = "lightblue"}
  if(i == 2){
    stats2$Rank_color_std[8:17] = "lightblue"}
  if(i == 3){
    stats2$Rank_color_std[10:34] = "lightblue"}
  if(i == 4){
    stats2$Rank_color_std[4:35] = "lightblue"}
  if(i == 4){
    stats2$Rank_color_std[4:41] = "lightblue"}
  if(i == 5){
    stats2$Rank_color_std[15:66] = "lightblue"}
  if(i == 5){
    stats2$Rank_color_std[15:74] = "lightblue"}

signif_stats_Yearly_20 = subset(Yearly_20_stats, !(Yearly_20_stats$Rank_color_std %in% c("black", "lightblue")))
nonsignif_stats_Yearly_201 = subset(Yearly_20_stats, Yearly_20_stats$Rank_color_std == "black")
nonsignif_stats_Yearly_202 = subset(Yearly_20_stats, Yearly_20_stats$Rank_color_std == "lightblue")
signif_pts0 = signif_stats_Yearly_20
signif_pts1 = nonsignif_stats_Yearly_201
signif_pts2 = nonsignif_stats_Yearly_202
signif_pts2["Label"] = NA
signif_pts2$Label[32] = "Alternative Options: 3/97 - 34/66"
signif_pts2$Label[70] = "Alternative Options: 3/97 - 40/60"
signif_pts0$Allocation = factor(signif_pts0$Allocation, levels = c(unique(signif_pts0$Allocation)))
col_pal <- c(signif_pts0$Rank_color_std)
col_pal2 <- c(signif_pts2$Rank_color_std)
vect = vector()
vect = append(vect, c(col_pal))
length
y120 = ggplot(data = signif_pts1, aes(x = std, y = mean, group = Method)) +
  facet_wrap(~Method, nrow=2, scales = "free") +
  geom_point(aes(x = std, y = mean, fill = Method)) + 
  geom_label(data=signif_pts0[c(2,6),], aes(x = 3, y = 2.75, color = Method,
                                   label = paste0("Lowest Risk: ", Num, "/", 100-Num, "\n",
                                     "Mean: ", round(mean, 4), ", ", 
                                     "SD: ", round(std, 4))),
             color = "darkgreen", size=4) +
  geom_label(data=signif_pts2[c(32,70),], aes(x = 3.75, y = 3.75, color = Method,
                                   label = Label),
             color = "blue", size=4) +
  geom_point(data = signif_pts2, aes(fill = Allocation1), shape = 21, size = 2.5) +
  geom_point(data = signif_pts0, aes(color=Allocation), size=4) +
  scale_fill_manual(values = col_pal2, limits = "Alternatives") +
  scale_color_manual(values = col_pal) +
  scale_shape_binned()+
  labs(title = "Mean vs Standard Deviation") +
  ylab("Mean") +
  xlab("Standard Deviation") +
  theme(plot.title = element_text(hjust = 0.5, size =15),
        axis.text = element_text(size = 10),
        axis.title = element_text(size=12),
        strip.text = element_text(size=12),
        legend.position = "bottom",
        legend.text = element_text(size=10, vjust = 0.5),
        legend.title = element_blank(),
        legend.box = "vertical",
        legend.margin=unit(0, "cm")) +
  guides(color = guide_legend(nrow = 2, byrow = TRUE, order=2),
         fill = guide_legend(order=1))

Yearly_20_stats$Allocation = factor(Yearly_20_stats$Allocation, levels = c(unique(Yearly_20_stats$Allocation)))

signif1 = subset(Yearly_20_stats, Yearly_20_stats$Rank_CI_color != "black")
signif2 = subset(Yearly_20_stats, Yearly_20_stats$Rank_CI_color == "black")
vect = vector()


y220 = ggplot(data = signif2, aes(x = Num, y = Lower_CI, xend = Num, yend = Upper_CI)) + 
  geom_segment() + 
  geom_segment(data = signif1, aes(colour = Allocation), size = 1.5) + ylab("95% CI") + xlab("Asset Allocation") + 
  facet_wrap(~Method, nrow=2) + 
  scale_color_manual(values = signif1$Rank_CI_color) + 
  labs(title = "95% Confidence Interval") + 
  geom_label(data=signif1[c(2,6),], aes(x = 17.5, y = 12.5, color = Method, label = paste0(
    "Largest Lower Bound: ", Num, "/", 100-Num, "\n","95% CI: ", round(Lower_CI,4))), color = "darkgreen", size=4) +
  theme(plot.title = element_text(hjust = 0.5, size =15),
        axis.text = element_text(size = 10),
        axis.title = element_text(size=12),
        strip.text = element_text(size=12),
        legend.position = "bottom",
        legend.text = element_text(size=10, vjust = 0.5),
        legend.title = element_blank()) +
  guides(color = guide_legend(nrow = 2, byrow = TRUE), fill = "none")



grid.arrange(y120,y220, ncol=2, top=text_grob("240 Month Returns", size = 18, face = "bold"))

```


# Yearly_20 GoF
```{r}

signif_GoF_Yearly_20 = subset(Yearly_20_GoF, Yearly_20_GoF$Rank_color_Value != "black" & Yearly_20_GoF$Type == "rrr")
nonsignif_GoF_Yearly_201 = subset(Yearly_20_GoF, Yearly_20_GoF$Rank_color_Value == "black" & Yearly_20_GoF$Type == "rrr")
signif_pts0 = signif_GoF_Yearly_20
signif_pts1 = nonsignif_GoF_Yearly_201
signif_pts0$Allocation = factor(signif_pts0$Allocation, levels = c(unique(signif_pts0$Allocation)))
col_pal <- c(signif_pts0$Rank_color_Value)

yr120 = ggplot(data = signif_pts1, aes(x = Num, y = Value, group = Method)) +
  facet_wrap(~Method, nrow=2, scales = "free") +
  geom_point(aes(x = Num, y = Value, fill = Method)) + 
  geom_label(data=signif_pts0[c(2,6),], aes(x = Num+20, y = Value-.03, color = Method,
                                   label = paste0("Largest Ratio: ", Num, "/", 100-Num, "\n",
                                    "Risk Reward Ratio = ", round(Value, 4))),
             color = "darkgreen", size=4) +
  geom_point(data = signif_pts0, aes(color=Allocation), size=4) +
  scale_color_manual(values = c("red", "green", "yellow", "orange", "green")) +
  labs(title = "Risk Reward Ratio") +
  ylab("Ratio") +
  xlab("Allocation (Large Cap)") +
  theme(plot.title = element_text(hjust = 0.5, size =15),
        axis.text = element_text(size = 10),
        axis.title = element_text(size=12),
        strip.text = element_text(size=12),
        legend.position = "bottom",
        legend.text = element_text(size=10, vjust = 0.5),
        legend.title = element_blank(),
        legend.box = "vertical",
        legend.margin=unit(0, "cm")) +
  guides(color = guide_legend(nrow = 5, byrow = TRUE, order=2),
         fill = "none")

signif_GoF_Yearly_20 = subset(Yearly_20_GoF, Yearly_20_GoF$Rank_color_Value != "black" & Yearly_20_GoF$Type == "sharpe1")
nonsignif_GoF_Yearly_201 = subset(Yearly_20_GoF, Yearly_20_GoF$Rank_color_Value == "black" & Yearly_20_GoF$Type == "sharpe1")
signif_pts0 = signif_GoF_Yearly_20
signif_pts1 = nonsignif_GoF_Yearly_201
signif_pts0$Allocation = factor(signif_pts0$Allocation, levels = c(unique(signif_pts0$Allocation)))
col_pal <- c(signif_pts0$Rank_color_Value)

yr220 = ggplot(data = signif_pts1, aes(x = Num, y = Value, group = Method)) +
  facet_wrap(~Method, nrow=2, scales = "free") +
  geom_point(aes(x = Num, y = Value, fill = Method)) + 
  geom_label(data=signif_pts0[c(2,6),], aes(x = Num+20, y = Value-.03, color = Method,
                                   label = paste0("Largest Ratio: ", Num, "/", 100-Num, "\n",
                                    "Sharpe Ratio = ", round(Value, 4))),
             color = "darkgreen", size=4) +
  geom_point(data = signif_pts0, aes(color=Allocation), size=4) +
  scale_color_manual(values = c("red", "green", "yellow", "orange", "green")) +
  labs(title = "Sharpe Ratio 1") +
  ylab("Ratio") +
  xlab("Allocation (Large Cap)") +
  theme(plot.title = element_text(hjust = 0.5, size =15),
        axis.text = element_text(size = 10),
        axis.title = element_text(size=12),
        strip.text = element_text(size=12),
        legend.position = "bottom",
        legend.text = element_text(size=10, vjust = 0.5),
        legend.title = element_blank(),
        legend.box = "vertical",
        legend.margin=unit(0, "cm")) +
  guides(color = guide_legend(nrow = 5, byrow = TRUE, order=2),
         fill = "none")


signif_GoF_Yearly_20 = subset(Yearly_20_GoF, Yearly_20_GoF$Rank_color_Value != "black" & Yearly_20_GoF$Type == "sharpe2")
nonsignif_GoF_Yearly_201 = subset(Yearly_20_GoF, Yearly_20_GoF$Rank_color_Value == "black" & Yearly_20_GoF$Type == "sharpe2")
signif_pts0 = signif_GoF_Yearly_20
signif_pts1 = nonsignif_GoF_Yearly_201
signif_pts0$Allocation = factor(signif_pts0$Allocation, levels = c(unique(signif_pts0$Allocation)))
col_pal <- c(signif_pts0$Rank_color_Value)
yr320 = ggplot(data = signif_pts1, aes(x = Num, y = Value, group = Method)) +
  facet_wrap(~Method, nrow=2, scales = "free") +
  geom_point(aes(x = Num, y = Value, fill = Method)) + 
  geom_label(data=signif_pts0[c(2,6),], aes(x = Num+20, y = Value-.03, color = Method,
                                   label = paste0("Largest Ratio: ", Num, "/", 100-Num, "\n",
                                    "Sharpe Ratio = ", round(Value, 4))),
             color = "darkgreen", size=4) +
  geom_point(data = signif_pts0, aes(color=Allocation), size=4) +
  scale_color_manual(values = c("red", "green", "yellow", "orange", "green")) +
  labs(title = "Sharpe Ratio 2") +
  ylab("Ratio") +
  xlab("Allocation (Large Cap)") +
  theme(plot.title = element_text(hjust = 0.5, size =15),
        axis.text = element_text(size = 10),
        axis.title = element_text(size=12),
        strip.text = element_text(size=12),
        legend.position = "bottom",
        legend.text = element_text(size=10, vjust = 0.5),
        legend.title = element_blank(),
        legend.box = "vertical",
        legend.margin=unit(0, "cm")) +
  guides(color = guide_legend(nrow = 5, byrow = TRUE, order=2),
         fill = "none")




grid.arrange(yr120,yr220,yr320, ncol=3, top=text_grob("240 Month Returns", size = 18, face = "bold"))

```

# Yearly_30 Stats
```{r}

Yearly_30_stats["Allocation1"] = NA
for(i in 1:202){
  if(Yearly_30_stats$Rank_color_std[i] == "lightblue"){
    Yearly_30_stats$Allocation1[i] = "Alternatives"}}


if(i == 1){
    stats2$Rank_color_std[6:13] = "lightblue"}
  if(i == 2){
    stats2$Rank_color_std[8:17] = "lightblue"}
  if(i == 3){
    stats2$Rank_color_std[10:34] = "lightblue"}
  if(i == 4){
    stats2$Rank_color_std[4:35] = "lightblue"}
  if(i == 4){
    stats2$Rank_color_std[4:41] = "lightblue"}
  if(i == 5){
    stats2$Rank_color_std[15:66] = "lightblue"}
  if(i == 5){
    stats2$Rank_color_std[15:74] = "lightblue"}

signif_stats_Yearly_30 = subset(Yearly_30_stats, !(Yearly_30_stats$Rank_color_std %in% c("black", "lightblue")))
nonsignif_stats_Yearly_301 = subset(Yearly_30_stats, Yearly_30_stats$Rank_color_std == "black")
nonsignif_stats_Yearly_302 = subset(Yearly_30_stats, Yearly_30_stats$Rank_color_std == "lightblue")
signif_pts0 = signif_stats_Yearly_30
signif_pts1 = nonsignif_stats_Yearly_301
signif_pts2 = nonsignif_stats_Yearly_302
signif_pts2["Label"] = NA
signif_pts2$Label[51] = "Alternative Options: 14/86 - 65/35"
signif_pts2$Label[110] = "Alternative Options: 14/86 - 73/27"
signif_pts0$Allocation = factor(signif_pts0$Allocation, levels = c(unique(signif_pts0$Allocation)))
col_pal <- c(signif_pts0$Rank_color_std)
col_pal2 <- c(signif_pts2$Rank_color_std)
vect = vector()
vect = append(vect, c(col_pal))
length
y130 = ggplot(data = signif_pts1, aes(x = std, y = mean, group = Method)) +
  facet_wrap(~Method, nrow=2, scales = "free") +
  geom_point(aes(x = std, y = mean, fill = Method)) + 
  geom_label(data=signif_pts0[c(2,6),], aes(x = std+1.5, y = mean, color = Method,
                                   label = paste0("Lowest Risk: ", Num, "/", 100-Num, "\n",
                                     "Mean: ", round(mean, 4), ", ", 
                                     "SD: ", round(std, 4))),
             color = "darkgreen", size=4) +
  geom_label(data=signif_pts2[c(51,110),], aes(x = 6.5, y = 11, color = Method,
                                   label = Label),
             color = "blue", size=4) +
  geom_point(data = signif_pts2, aes(fill = Allocation1), shape = 21, size = 2.5) +
  geom_point(data = signif_pts0, aes(color=Allocation), size=4) +
  scale_fill_manual(values = col_pal2, limits = "Alternatives") +
  scale_color_manual(values = col_pal) +
  scale_shape_binned()+
  labs(title = "Mean vs Standard Deviation") +
  ylab("Mean") +
  xlab("Standard Deviation") +
  theme(plot.title = element_text(hjust = 0.5, size =15),
        axis.text = element_text(size = 10),
        axis.title = element_text(size=12),
        strip.text = element_text(size=12),
        legend.position = "bottom",
        legend.text = element_text(size=10, vjust = 0.5),
        legend.title = element_blank(),
        legend.box = "vertical",
        legend.margin=unit(0, "cm")) +
  guides(color = guide_legend(nrow = 2, byrow = TRUE, order=2),
         fill = guide_legend(order=1))

Yearly_30_stats$Allocation = factor(Yearly_30_stats$Allocation, levels = c(unique(Yearly_30_stats$Allocation)))

signif1 = subset(Yearly_30_stats, Yearly_30_stats$Rank_CI_color != "black")
signif2 = subset(Yearly_30_stats, Yearly_30_stats$Rank_CI_color == "black")

y230 = ggplot(data = signif2, aes(x = Num, y = Lower_CI, xend = Num, yend = Upper_CI)) + 
  geom_segment() + 
  geom_segment(data = signif1, aes(colour = Allocation), size = 1.5) + ylab("95% CI") + xlab("Asset Allocation") + 
  facet_wrap(~Method, nrow=2) + 
  scale_color_manual(values = signif1$Rank_CI_color) + 
  labs(title = "95% Confidence Interval") + 
  geom_label(data=signif1[c(3,6),], aes(x = 75, y = -2, color = Method, label = paste0(
    "Largest Lower Bound: ", Num, "/", 100-Num, "\n","95% CI: ", round(Lower_CI,4))), color = "darkgreen", size=4) +
  theme(plot.title = element_text(hjust = 0.5, size =15),
        axis.text = element_text(size = 10),
        axis.title = element_text(size=12),
        strip.text = element_text(size=12),
        legend.position = "bottom",
        legend.text = element_text(size=10, vjust = 0.5),
        legend.title = element_blank()) +
  guides(color = guide_legend(nrow = 2, byrow = TRUE), fill = "none")



grid.arrange(y130,y230, ncol=2, top=text_grob("360 Month Returns", size = 18, face = "bold"))

```

# Yearly_30 GoF
```{r}

signif_GoF_Yearly_30 = subset(Yearly_30_GoF, Yearly_30_GoF$Rank_color_Value != "black" & Yearly_30_GoF$Type == "rrr")
nonsignif_GoF_Yearly_301 = subset(Yearly_30_GoF, Yearly_30_GoF$Rank_color_Value == "black" & Yearly_30_GoF$Type == "rrr")
signif_pts0 = signif_GoF_Yearly_30
signif_pts1 = nonsignif_GoF_Yearly_301
signif_pts0$Allocation = factor(signif_pts0$Allocation, levels = c(unique(signif_pts0$Allocation)))
col_pal <- c(signif_pts0$Rank_color_Value)

yr130 = ggplot(data = signif_pts1, aes(x = Num, y = Value, group = Method)) +
  facet_wrap(~Method, nrow=2, scales = "free") +
  geom_point(aes(x = Num, y = Value, fill = Method)) + 
  geom_label(data=signif_pts0[c(2,6),], aes(x = Num+20, y = Value-.03, color = Method,
                                   label = paste0("Largest Ratio: ", Num, "/", 100-Num, "\n",
                                    "Risk Reward Ratio = ", round(Value, 4))),
             color = "darkgreen", size=4) +
  geom_point(data = signif_pts0, aes(color=Allocation), size=4) +
  scale_color_manual(values = c("red", "green", "yellow", "orange", "green")) +
  labs(title = "Risk Reward Ratio") +
  ylab("Ratio") +
  xlab("Allocation (Large Cap)") +
  theme(plot.title = element_text(hjust = 0.5, size =15),
        axis.text = element_text(size = 10),
        axis.title = element_text(size=12),
        strip.text = element_text(size=12),
        legend.position = "bottom",
        legend.text = element_text(size=10, vjust = 0.5),
        legend.title = element_blank(),
        legend.box = "vertical",
        legend.margin=unit(0, "cm")) +
  guides(color = guide_legend(nrow = 5, byrow = TRUE, order=2),
         fill = "none")

signif_GoF_Yearly_30 = subset(Yearly_30_GoF, Yearly_30_GoF$Rank_color_Value != "black" & Yearly_30_GoF$Type == "sharpe1")
nonsignif_GoF_Yearly_301 = subset(Yearly_30_GoF, Yearly_30_GoF$Rank_color_Value == "black" & Yearly_30_GoF$Type == "sharpe1")
signif_pts0 = signif_GoF_Yearly_30
signif_pts1 = nonsignif_GoF_Yearly_301
signif_pts0$Allocation = factor(signif_pts0$Allocation, levels = c(unique(signif_pts0$Allocation)))
col_pal <- c(signif_pts0$Rank_color_Value)

yr230 = ggplot(data = signif_pts1, aes(x = Num, y = Value, group = Method)) +
  facet_wrap(~Method, nrow=2, scales = "free") +
  geom_point(aes(x = Num, y = Value, fill = Method)) + 
  geom_label(data=signif_pts0[c(2,6),], aes(x = Num+20, y = Value-.03, color = Method,
                                   label = paste0("Largest Ratio: ", Num, "/", 100-Num, "\n",
                                    "Sharpe Ratio = ", round(Value, 4))),
             color = "darkgreen", size=4) +
  geom_point(data = signif_pts0, aes(color=Allocation), size=4) +
  scale_color_manual(values = c("red", "green", "yellow", "orange", "green")) +
  labs(title = "Sharpe Ratio 1") +
  ylab("Ratio") +
  xlab("Allocation (Large Cap)") +
  theme(plot.title = element_text(hjust = 0.5, size =15),
        axis.text = element_text(size = 10),
        axis.title = element_text(size=12),
        strip.text = element_text(size=12),
        legend.position = "bottom",
        legend.text = element_text(size=10, vjust = 0.5),
        legend.title = element_blank(),
        legend.box = "vertical",
        legend.margin=unit(0, "cm")) +
  guides(color = guide_legend(nrow = 5, byrow = TRUE, order=2),
         fill = "none")


signif_GoF_Yearly_30 = subset(Yearly_30_GoF, Yearly_30_GoF$Rank_color_Value != "black" & Yearly_30_GoF$Type == "sharpe2")
nonsignif_GoF_Yearly_301 = subset(Yearly_30_GoF, Yearly_30_GoF$Rank_color_Value == "black" & Yearly_30_GoF$Type == "sharpe2")
signif_pts0 = signif_GoF_Yearly_30
signif_pts1 = nonsignif_GoF_Yearly_301
signif_pts0$Allocation = factor(signif_pts0$Allocation, levels = c(unique(signif_pts0$Allocation)))
col_pal <- c(signif_pts0$Rank_color_Value)
yr330 = ggplot(data = signif_pts1, aes(x = Num, y = Value, group = Method)) +
  facet_wrap(~Method, nrow=2, scales = "free") +
  geom_point(aes(x = Num, y = Value, fill = Method)) + 
  geom_label(data=signif_pts0[c(2,6),], aes(x = Num+20, y = Value-.03, color = Method,
                                   label = paste0("Largest Ratio: ", Num, "/", 100-Num, "\n",
                                    "Sharpe Ratio = ", round(Value, 4))),
             color = "darkgreen", size=4) +
  geom_point(data = signif_pts0, aes(color=Allocation), size=4) +
  scale_color_manual(values = c("red", "green", "yellow", "orange", "green")) +
  labs(title = "Sharpe Ratio 2") +
  ylab("Ratio") +
  xlab("Allocation (Large Cap)") +
  theme(plot.title = element_text(hjust = 0.5, size =15),
        axis.text = element_text(size = 10),
        axis.title = element_text(size=12),
        strip.text = element_text(size=12),
        legend.position = "bottom",
        legend.text = element_text(size=10, vjust = 0.5),
        legend.title = element_blank(),
        legend.box = "vertical",
        legend.margin=unit(0, "cm")) +
  guides(color = guide_legend(nrow = 5, byrow = TRUE, order=2),
         fill = "none")




grid.arrange(yr130,yr230,yr330, ncol=3, top=text_grob("360 Month Returns", size = 18, face = "bold"))

```
# Probability of similar losses
```{r}
# Portfolio 60/40
sig_loss1 = qnorm(0.05, mean = mean(Yearly_Data$Folio60), sd = sqrt(var(Yearly_Data$Folio60)), lower.tail = TRUE)
sig_loss2 = qnorm(0.01, mean = mean(Yearly_Data$Folio60), sd = sqrt(var(Yearly_Data$Folio60)), lower.tail = TRUE)
sig_loss3 = qnorm(0.001, mean = mean(Yearly_Data$Folio60), sd = sqrt(var(Yearly_Data$Folio60)), lower.tail = TRUE)
sig_loss4 = qnorm(0.0001, mean = mean(Yearly_Data$Folio60), sd = sqrt(var(Yearly_Data$Folio60)), lower.tail = TRUE)

significant_losses = subset(Yearly_Data, Yearly_Data$Folio60 <= sig_loss1)[c("Date", "Folio60")]
require(zoo)
significant_losses["Year"] <- year(significant_losses$Date)
significant_losses["Month"] = months(significant_losses$Date)
significant_losses$Month <- factor(significant_losses$Month, levels = rev(month.name))
significant_losses$Year <- factor(significant_losses$Year, levels = unique(year(significant_losses$Date)))
significant_losses["Probability"] = NA


for(i in 1:54){
  if(significant_losses$Folio60[i] < sig_loss1){
    significant_losses$Probability[i] = "< 5%"}
  if(significant_losses$Folio60[i] < sig_loss2){
    significant_losses$Probability[i] = "< 1%"}
  if(significant_losses$Folio60[i] < sig_loss3){
    significant_losses$Probability[i] = "< 0.1%"}
  if(significant_losses$Folio60[i] < sig_loss4){
    significant_losses$Probability[i] = "< 0.01%"}}

significant_losses$Probability <- factor(significant_losses$Probability, levels = c("< 5%", "< 1%", "< 0.1%", "< 0.01%"))

significant_losses %>%
  ggplot()+
  geom_col(aes(x=abs(Folio60), y = Month, fill = Probability)) +
  scale_x_continuous(breaks = c(0, 0.1, 0.2, 0.3, 0.4, 0.5)) +
  facet_wrap(~as.character(Year)) +
  labs(title="12-Month Significant Losses on the 60/40 Portfolio",
  x = "Investment Loss")+
  scale_fill_manual(values  = c("< 5%" = "yellow",
                                "< 1%" = "orange",
                                "< 0.1%" = "orangered1",
                                "< 0.01%" = "red2")) +
  geom_text(aes(x = abs(Folio60), y = Month, label = round(abs(Folio60), 4)), hjust=1) +
  theme(plot.title = element_text(hjust = 0.5),
        strip.text = element_text(size = 15),
        axis.text = element_text(size = 12),
        axis.title = element_text(size = 15),
        title =element_text(size=18, face='bold'),
        legend.text = element_text(size = 12))


# Prob from simulation
weighted_TR <- read_excel("Pension Investment Calculation (Annual) MRP600 Sim.xlsx", 
    sheet = "Weighted TR", col_names = FALSE)

list = data.frame(matrix(ncol=1, nrow = 30000))
for(i in 1:30){
  x= 1000 * (i-1) + 1
  y = 1000 * i
  list[x:y,1] = weighted_TR[,i]}

pnorm(-0.16, mean = mean(list[,1]), sd = sd(list[,1]), lower.tail = TRUE)
# 0.01316642

# Prob from historical data
Data = Yearly_Data$Folio60[1:1152]
pnorm(-0.16, mean = mean(Data), sd = sd(Data), lower.tail = TRUE)
# 0.02569

Data1 = Monthly_Data$Folio60[1:1152]
pnorm(-0.010837929, mean = mean(Data1), sd = sd(Data1), lower.tail = TRUE)

Annual_Data = data.frame(matrix(nrow=96, ncol=1))
x=1
for(i in 1:1152){
  if((i-1)%%12==0){
    Annual_Data[x,1] = Data[i]
    x = x + 1}}
pnorm(-0.16, mean = mean(Annual_Data[,1]), sd = sd(Annual_Data[,1]), lower.tail = TRUE)
# 0.02037196

# Annual
Annual <- read_excel("Project 2 Historical Data.xlsx", 
    sheet = "60-40 Returns Annual", range = "E10:E107")

pnorm(-0.16, mean = sum(Annual[1:96,1])/96, sd = sqrt(var(Annual[1:96,1])), lower.tail = TRUE)



```
# Pension
```{r, warning=FALSE}
options(scipen = 7)
US_TR <- read_excel("Pension Investment Calculation (Annual) MRP600 Sim.xlsx", 
    sheet = "US TR", range = "B1:AE1000", 
    col_names = FALSE)
for(i in 1:30){
  colnames(US_TR)[i] = paste0("Year",i)}

FIXED_TR <- read_excel("Pension Investment Calculation (Annual) MRP600 Sim.xlsx", 
    sheet = "FIXED TR", range = "B1:AE1000", 
    col_names = FALSE)
for(i in 1:30){
  colnames(FIXED_TR)[i] = paste0("Year",i)}

Weighted_TR  <- read_excel("Pension Investment Calculation (Annual) MRP600 Sim.xlsx", 
    sheet = "Weighted TR", range = "B1:AE1000", 
    col_names = FALSE)
for(i in 1:30){
  colnames(Weighted_TR)[i] = paste0("Year",i)}

Pension <- read_excel("Pension Investment Calculation (Annual) MRP600 Sim.xlsx", 
    sheet = "Pension Fund Balance", range = "C2:AG1007", 
    col_names = FALSE)
for(i in 0:30){
  colnames(Pension)[i+1] = paste0("Year",i)}
payments = Pension[2,2:31]
Pension = Pension[6:1005,]
Pension$Year0 = as.integer(Pension$Year0)


for(i in 0:100){
  alpha = i/100
  weight = Weighted_TR
  weight[,1:30] = NA
  for(j in 1:30){
    bind = cbind(data.frame(US_TR[,j]), data.frame(FIXED_TR[,j]))
    colnames(bind) = c("US", "FIX")
    bind = bind %>%
      mutate("weight" = bind$US * alpha + bind$FIX * (1-alpha))
    if(j == 1){
      weight = cbind(data.frame(bind[,3]), data.frame(weight[,2:30]))}
    if(j == 30){
      weight = cbind(data.frame(weight[,1:29]), data.frame(bind[,3]))}
    if(j %in% c(seq(2,29,1))){
      weight = cbind(data.frame(weight[,1:j-1]), data.frame(bind[,3]),
                     data.frame(weight[,c((j+1):30)]))}
    colnames(weight)[j] = paste0("Year", j)}
  assign(paste0("Weighted_", i), weight)}

insolvency_rate = 0.0700
for(i in 0:100){
  pension = Pension
  pension[,2:31] = NA
  weight = get(paste0("Weighted_", i))
  for(j in 1:30){
    frame = data.frame(matrix(ncol=2,nrow=1000))
    frame[,1] = c(seq(1,1000,1))
    frame[,2] = c(rep(payments[1,j],1000))
    data = cbind(data.frame(frame[,1]), data.frame(pension[,j]), data.frame(weight[,j]), data.frame(frame[,2]))
    colnames(data) = c("Num", "Last_Year", "Weight", "payment")
    sub1 = subset(data, data$Last_Year > 0)
    sub2 = subset(data, data$Last_Year < 0)
    sub1 = sub1 %>%
      mutate("Balance" = sub1$Last_Year * (1+sub1$Weight) - sub1$payment)
    if(length(sub1$Num) != 1000){
      sub2 = sub2 %>%
        mutate("Balance" = sub2$Last_Year * (1 + insolvency_rate) - sub2$payment)}
    data = rbind(sub1, sub2)
    data_num = order(data$Num)
    data = data[c(data_num),]
    pension[1:1000, j+1] = data$Balance[1:1000]}
  assign(paste0("Pension_", i), pension)}
  
for(i in 0:100){
  end = get(paste0("Pension_", i))
  if(i == 0){
    End_Balance = data.frame(end$Year30)}
  if(i != 0){
    End_Balance = cbind(End_Balance, data.frame(end$Year30))}
  colnames(End_Balance)[i+1] = paste0("Pension_", i)}

vect0 = vector()
for(i in 0:100){
  vect0 = append(vect0, paste0("Large Cap: ", i, "% | ", "Fixed: ", 100-i, "%"))}

ci = 0.05*525
End_stats = data.frame(matrix(nrow = 101, ncol = 13))
colnames(End_stats) = c("Allocation", "Num", "Mean", "Std", "P[0 < Balalce]", "P[-26.25 < Balalce]", "Average Deficit", "Under_Std", "Average Excess", "Over_Std", "Conditionally Expected Deficit", "Conditionally Expected Excess", "Expected Difference" )
End_stats$Allocation = c(vect0)
End_stats$Allocation = factor(End_stats$Allocation, levels = c(End_stats$Allocation))
End_stats$Num = c(seq(0,100,1))

for(i in 0:100){
  End = End_Balance[,i+1]
  end_under = subset(End_Balance[, i+1], End_Balance[, i+1] < 0)
  end_over = subset(End_Balance[, i+1], End_Balance[, i+1] > 0)
  End_stats$Mean[i+1] = mean(End)
  End_stats$Std[i+1] = sqrt(var(End))
  End_stats$`P[0 < Balalce]`[i+1] = pnorm(0, mean = End_stats$Mean[i+1], sd = End_stats$Std[i+1], lower.tail = FALSE)
  End_stats$`P[-26.25 < Balalce]`[i+1] = pnorm(-26.25, mean = End_stats$Mean[i+1], sd = End_stats$Std[i+1], lower.tail = FALSE)
  End_stats$`Average Deficit`[i+1] = mean(end_under)
  End_stats$Under_Std[i+1] = sqrt(var(end_under))
  End_stats$`Average Excess`[i+1] = mean(end_over)
  End_stats$Over_Std[i+1] = sqrt(var(end_over))
  End_stats$`Conditionally Expected Deficit`[i+1] = End_stats$`Average Deficit`[i+1] * (1 - End_stats$`P[0 < Balalce]`)
  End_stats$`Conditionally Expected Excess`[i+1] = End_stats$`Average Excess`[i+1] * End_stats$`P[0 < Balalce]`
  End_stats$`Expected Difference`[i+1] = End_stats$`Conditionally Expected Deficit`[i+1] + End_stats$`Conditionally Expected Excess`[i+1]}



prob = data.frame(End_stats[,c(1,2,5)])

vect0 = vector()
vect0 = append(vect0, c(1,61,101))
vect1 = vect0
vect2 = vect0
vect3 = vect0
vect4 = vect0
vect5 = vect0
vect6 = vect0
for(i in 0:100){
  if(End_stats$Std[i+1] == max(End_stats$Std) |
     End_stats$Std[i+1] == min(End_stats$Std)){
    vect0 = append(vect0, i+1)}
  vect0 = sort(unique(vect0))
  sig0 = End_stats[c(vect0),]
  sig0 = sig0 %>%
    mutate("Rank" = rank(sig0$Std))
  sig0["Color"] = NA
  for(j in 1:length(sig0$Rank)){
    if(sig0$Rank[j] == 1){
      sig0$Color[j] = "green"}
    if(sig0$Rank[j] == 2){
      sig0$Color[j] = "yellow"}
    if(sig0$Rank[j] == 3){
      sig0$Color[j] = "red"}}
  if(End_stats$`P[0 < Balalce]`[i+1] == max(End_stats$`P[0 < Balalce]`) |
     End_stats$`P[0 < Balalce]`[i+1] == min(End_stats$`P[0 < Balalce]`)){
    vect1 = append(vect1, i+1)}
  vect1 = sort(unique(vect1))
  sig1 = End_stats[c(vect1),]
  sig1 = sig1 %>%
    mutate("Rank" = 5 - rank(sig1$`P[0 < Balalce]`))
  sig1["Color"] = NA
  for(j in 1:length(sig1$Rank)){
    if(sig1$Rank[j] == 1){
      sig1$Color[j] = "green"}
    if(sig1$Rank[j] == 2){
      sig1$Color[j] = "yellow"}
    if(sig1$Rank[j] == 3){
      sig1$Color[j] = "orange"}
    if(sig1$Rank[j] == 4){
      sig1$Color[j] = "red"}}
  if(End_stats$`Average Deficit`[i+1] == max(End_stats$`Average Deficit`) |
     End_stats$`Average Deficit`[i+1] == min(End_stats$`Average Deficit`)){
    vect2 = append(vect2, i+1)}
  vect2 = sort(unique(vect2))
  sig2 = End_stats[c(vect2),]
  sig2 = sig2 %>%
    mutate("Rank" = 5-rank(sig2$`Average Deficit`))
  sig2["Color"] = NA
  for(j in 1:length(sig2$Rank)){
    if(sig2$Rank[j] == 1){
      sig2$Color[j] = "green"}
    if(sig2$Rank[j] == 2){
      sig2$Color[j] = "yellow"}
    if(sig2$Rank[j] == 3){
      sig2$Color[j] = "orange"}
    if(sig2$Rank[j] == 4){
      sig2$Color[j] = "red"}}
  if(End_stats$`Average Excess`[i+1] == max(End_stats$`Average Excess`) |
     End_stats$`Average Excess`[i+1] == min(End_stats$`Average Excess`)){
    vect3 = append(vect3, i+1)}
  vect3 = sort(unique(vect3))
  sig3 = End_stats[c(vect3),]
  sig3 = sig3 %>%
    mutate("Rank" = rank(sig3$`Average Excess`))
  sig3["Color"] = NA
  for(j in 1:length(sig3$Rank)){
    if(sig3$Rank[j] == 1){
      sig3$Color[j] = "green"}
    if(sig3$Rank[j] == 2){
      sig3$Color[j] = "yellow"}
    if(sig3$Rank[j] == 3){
      sig3$Color[j] = "red"}}
  if(End_stats$`Conditionally Expected Deficit`[i+1] == max(End_stats$`Conditionally Expected Deficit`) |
     End_stats$`Conditionally Expected Deficit`[i+1] == min(End_stats$`Conditionally Expected Deficit`)){
    vect4 = append(vect4, i+1)}
  vect4 = sort(unique(vect4))
  sig4 = End_stats[c(vect4),]
  sig4 = sig4 %>%
    mutate("Rank" = 5-rank(sig4$`Conditionally Expected Deficit`))
  sig4["Color"] = NA
  for(j in 1:length(sig4$Rank)){
    if(sig4$Rank[j] == 1){
      sig4$Color[j] = "green"}
    if(sig4$Rank[j] == 2){
      sig4$Color[j] = "yellow"}
    if(sig4$Rank[j] == 3){
      sig4$Color[j] = "orange"}
    if(sig4$Rank[j] == 4){
      sig4$Color[j] = "red"}}
  if(End_stats$`Conditionally Expected Excess`[i+1] == max(End_stats$`Conditionally Expected Excess`) |
     End_stats$`Conditionally Expected Excess`[i+1] == min(End_stats$`Conditionally Expected Excess`)){
    vect5 = append(vect5, i+1)}
  vect5 = sort(unique(vect5))
  sig5 = End_stats[c(vect5),]
  sig5 = sig5 %>%
    mutate("Rank" = rank(sig5$`Conditionally Expected Excess`))
  sig5["Color"] = NA
  for(j in 1:length(sig5$Rank)){
    if(sig5$Rank[j] == 1){
      sig5$Color[j] = "green"}
    if(sig5$Rank[j] == 2){
      sig5$Color[j] = "yellow"}
    if(sig5$Rank[j] == 3){
      sig5$Color[j] = "red"}}
  if(End_stats$`Expected Difference`[i+1] == max(End_stats$`Expected Difference`) |
     End_stats$`Expected Difference`[i+1] == min(End_stats$`Expected Difference`)){
    vect6 = append(vect6, i+1)}
  vect6 = sort(unique(vect6))
  sig6 = End_stats[c(vect6),]
  sig6 = sig6 %>%
    mutate("Rank" = rank(sig6$`Expected Difference`))
  sig6["Color"] = NA
  for(j in 1:length(sig6$Rank)){
    if(sig6$Rank[j] == 1){
      sig6$Color[j] = "green"}
    if(sig6$Rank[j] == 2){
      sig6$Color[j] = "yellow"}
    if(sig6$Rank[j] == 3){
      sig6$Color[j] = "red"}}}
  

a = ggplot(data = End_stats, aes(x = Std, y = Mean)) +
  geom_point() + 
  geom_label(data=sig0[1,], aes(x = Std+250, y = Mean + 1000,
                                   label = paste0("Smallest Risk: ", Num, "/", 100-Num, "\n",
                                    "SD = ", round(Std, 4))),
             color = "darkgreen", size=4) +
  geom_point(data = sig0, aes(color=Allocation), size=4) +
  scale_color_manual(values = sig0$Color) +
  labs(title = "Mean vs Standard Deviation") +
  ylab("Mean") +
  xlab("Standard Deviation") +
  theme(plot.title = element_text(hjust = 0.5, size =15),
        axis.text = element_text(size = 10),
        axis.title = element_text(size=12),
        strip.text = element_text(size=12),
        legend.position = "right",
        legend.text = element_text(size=10, vjust = 0.5),
        legend.title = element_blank(),
        legend.box = "vertical",
        legend.margin=unit(0, "cm")) +
  guides(color = guide_legend(nrow = 4, byrow = TRUE))

  
b = ggplot(data = End_stats, aes(x = Num, y = `P[0 < Balalce]`)) +
  geom_point() + 
  geom_label(data=sig1[2,], aes(x = Num, y = `P[0 < Balalce]`-0.05,
                                   label = paste0("Highest Probability: ", Num, "/", 100-Num, "\n",
                                    "P[0 < Balance] = ", 100 * round(`P[0 < Balalce]`, 4), "%")),
             color = "darkgreen", size=4) +
  geom_point(data = sig1, aes(color=Allocation), size=4) +
  scale_color_manual(values = sig1$Color) +
  labs(title = "Fund Sufficiency") +
  ylab("Probability") +
  xlab("Asset Allocation") +
  theme(plot.title = element_text(hjust = 0.5, size =15),
        axis.text = element_text(size = 10),
        axis.title = element_text(size=12),
        strip.text = element_text(size=12),
        legend.position = "right",
        legend.text = element_text(size=10, vjust = 0.5),
        legend.title = element_blank(),
        legend.box = "vertical",
        legend.margin=unit(0, "cm")) +
  guides(color = guide_legend(nrow = 4, byrow = TRUE))

sig4 = sig4 %>%
  mutate("Value" = sig4$`Conditionally Expected Deficit`) %>%
  mutate("Type" = "Deficit")

sig5 = sig5 %>%
  mutate("Value" = sig5$`Conditionally Expected Excess`) %>%
  mutate("Type" = "Surplus")

sig45 = rbind(sig4, sig5)

data1 = End_stats[, c(1,2,11)]
data2 = End_stats[, c(1,2,12)]

data1 = data1 %>%
  mutate("Value" = data1$`Conditionally Expected Deficit`) %>%
  mutate("Type" = "Deficit")

data1 = data1[,c(1,2,4,5)]

data2 = data2 %>%
  mutate("Value" = data2$`Conditionally Expected Excess`) %>%
  mutate("Type" = "Surplus")

data2 = data2[,c(1,2,4,5)]

data12 = rbind(data1, data2)

data12["Fill"] = NA
data12$Fill[1:101] = "purple"
data12$Fill[102:202] = "black"


for(i in c(1,2,5,6)){
  levels(sig45$Allocation) <- c(levels(sig45$Allocation), 
                                c(paste0(sig45$Allocation[i], " - (", sig45$Type[i],")")))
  sig45$Allocation[i] = paste0(sig45$Allocation[i], " - (", sig45$Type[i],")")}

sig45["start"] = NA
sig45["unit"] = NA
sig45["nudge_x"] = NA
sig45["nudge_y"] = NA

for(i in c(2,5)){
  if(i == 2){
    sig45$start[i] = "Deficit"
    sig45$unit[i] = "-$"
    sig45$nudge_x[i] = 0
    sig45$nudge_y[i] = 1400}
  if(i == 5){
    sig45$start[i] = "Surplus"
    sig45$unit[i] = "$"
    sig45$nudge_x[i] = 10
    sig45$nudge_y[i] = 900}}

data12$Fill = factor(data12$Fill, levels = c("purple", "black"))

c = ggplot(data = data12, aes(x = Num, y = Value, color = factor(Type))) +
  geom_point() +
  # geom_point(data = data12[1:101,], aes(x=Num, y=Value), color = "purple") + 
  geom_label(data=sig45[c(2,5),], aes(x = Num + nudge_x, y = nudge_y,
                                   label = paste0("Smallest ", start, ": ", Num, "/", 100-Num, "\n",
                                    "Amount = ", unit, round(abs(Value), 4))),
             color = "darkgreen", size=4) +
  geom_point(data = sig45, aes(x=Num, y = Value, color=Allocation), size=4) +
  scale_color_manual(values =  c("purple", "yellow", "green", "red", "green", "orange", "yellow", "black", "green")) +
  # scale_discrete_manual(aesthetics = c("colour", "fill"), values = c(unique(data12$Fill)), labels = c("Average Deficit", "Average Excess")) +
  labs(title = "Deficit and Surplus Funds") +
  ylab("Amount ($ Millions)") +
  xlab("Asset Allocation") +
  theme(plot.title = element_text(hjust = 0.5, size =15),
        axis.text = element_text(size = 10),
        axis.title = element_text(size=12),
        strip.text = element_text(size=12),
        legend.position = "right",
        legend.text = element_text(size=10, vjust = 0.5),
        legend.title = element_blank(),
        legend.box = "vertical",
        legend.margin=unit(0, "cm")) +
  guides(color = guide_legend(nrow = 9, byrow = TRUE))
  
grid.arrange(a,b,c, ncol=1, top=text_grob("Pension", size = 18, face = "bold", hjust = 1.4))
```


# Top up
```{r, warning=FALSE}

insolvency_rate = 0.0700
for(i in 0:100){
  Top_up = Pension
  Top_up[,2:31] = NA
  Top_up$Year0 = c(rep(700, 1000)) 
  weight = get(paste0("Weighted_", i))
  for(j in 1:30){
    frame = data.frame(matrix(ncol=2,nrow=1000))
    frame[,1] = c(seq(1,1000,1))
    frame[,2] = c(rep(payments[1,j],1000))
    data = cbind(data.frame(frame[,1]), data.frame(Top_up[,j]), data.frame(weight[,j]), data.frame(frame[,2]))
    colnames(data) = c("Num", "Last_Year", "Weight", "payment")
    sub1 = subset(data, data$Last_Year > 0)
    sub2 = subset(data, data$Last_Year < 0)
    sub1 = sub1 %>%
      mutate("Balance" = sub1$Last_Year * (1+sub1$Weight) - sub1$payment)
    if(length(sub1$Num) != 1000){
      sub2 = sub2 %>%
        mutate("Balance" = sub2$Last_Year * (1 + insolvency_rate) - sub2$payment)}
    data = rbind(sub1, sub2)
    data_num = order(data$Num)
    data = data[c(data_num),]
    Top_up[1:1000, j+1] = data$Balance[1:1000]}
  assign(paste0("Top_up_", i), Top_up)}
  
for(i in 0:100){
  end1 = get(paste0("Top_up_", i))
  if(i == 0){
    End1_Balance = data.frame(end1$Year30)}
  if(i != 0){
    End1_Balance = cbind(End1_Balance, data.frame(end1$Year30))}
  colnames(End1_Balance)[i+1] = paste0("Top_up_", i)}

vect0 = vector()
for(i in 0:100){
  vect0 = append(vect0, paste0("Large Cap: ", i, "% | ", "Fixed: ", 100-i, "%"))}

ci = 0.05*525
End1_stats = data.frame(matrix(nrow = 101, ncol = 13))
colnames(End1_stats) = c("Allocation", "Num", "Mean", "Std", "P[0 < Balalce]", "P[-26.25 < Balalce]", "Average Deficit", "Under_Std", "Average Excess", "Over_Std", "Conditionally Expected Deficit", "Conditionally Expected Excess", "Expected Difference" )
End1_stats$Allocation = c(vect0)
End1_stats$Allocation = factor(End1_stats$Allocation, levels = c(End1_stats$Allocation))
End1_stats$Num = c(seq(0,100,1))

for(i in 0:100){
  End1 = End1_Balance[,i+1]
  end1_under = subset(End1_Balance[, i+1], End1_Balance[, i+1] < 0)
  end1_over = subset(End1_Balance[, i+1], End1_Balance[, i+1] > 0)
  End1_stats$Mean[i+1] = mean(End1)
  End1_stats$Std[i+1] = sqrt(var(End1))
  End1_stats$`P[0 < Balalce]`[i+1] = pnorm(0, mean = End1_stats$Mean[i+1], sd = End1_stats$Std[i+1], lower.tail = FALSE)
  End1_stats$`P[-26.25 < Balalce]`[i+1] = pnorm(-26.25, mean = End1_stats$Mean[i+1], sd = End1_stats$Std[i+1], lower.tail = FALSE)
  End1_stats$`Average Deficit`[i+1] = mean(end1_under)
  End1_stats$Under_Std[i+1] = sqrt(var(end1_under))
  End1_stats$`Average Excess`[i+1] = mean(end1_over)
  End1_stats$Over_Std[i+1] = sqrt(var(end1_over))
  End1_stats$`Conditionally Expected Deficit`[i+1] = End1_stats$`Average Deficit`[i+1] * (1 - End1_stats$`P[0 < Balalce]`)
  End1_stats$`Conditionally Expected Excess`[i+1] = End1_stats$`Average Excess`[i+1] * End1_stats$`P[0 < Balalce]`
  End1_stats$`Expected Difference`[i+1] = End1_stats$`Conditionally Expected Deficit`[i+1] + End1_stats$`Conditionally Expected Excess`[i+1]}

prob = cbind(prob, data.frame(End1_stats[,c(1,2,5)]))
prob = prob[,c(1,2,3,6)]
colnames(prob)[3:4] = c("Pension", "Top-Up")
prob = prob %>%
  mutate("Improvement" = (prob$`Top-Up` - prob$Pension)/prob$Pension)

prob
vect0 = vector()
vect0 = append(vect0, c(1,61,101))
vect1 = vect0
vect2 = vect0
vect3 = vect0
vect4 = vect0
vect5 = vect0
vect6 = vect0
for(i in 0:100){
  if(End1_stats$Std[i+1] == max(End1_stats$Std) |
     End1_stats$Std[i+1] == min(End1_stats$Std)){
    vect0 = append(vect0, i+1)}
  vect0 = sort(unique(vect0))
  sig0 = End1_stats[c(vect0),]
  sig0 = sig0 %>%
    mutate("Rank" = rank(sig0$Std))
  sig0["Color"] = NA
  for(j in 1:length(sig0$Rank)){
    if(sig0$Rank[j] == 1){
      sig0$Color[j] = "green"}
    if(sig0$Rank[j] == 2){
      sig0$Color[j] = "yellow"}
    if(sig0$Rank[j] == 3){
      sig0$Color[j] = "orange"}
    if(sig0$Rank[j] == 4){
      sig0$Color[j] = "red"}}
  if(End1_stats$`P[0 < Balalce]`[i+1] == max(End1_stats$`P[0 < Balalce]`) |
     End1_stats$`P[0 < Balalce]`[i+1] == min(End1_stats$`P[0 < Balalce]`)){
    vect1 = append(vect1, i+1)}
  vect1 = sort(unique(vect1))
  sig1B = End1_stats[c(vect1),]
  sig1B = sig1B %>%
    mutate("Rank" = 5 - rank(sig1B$`P[0 < Balalce]`))
  sig1B["Color"] = NA
  for(j in 1:length(sig1B$Rank)){
    if(sig1B$Rank[j] == 1){
      sig1B$Color[j] = "green"}
    if(sig1B$Rank[j] == 2){
      sig1B$Color[j] = "yellow"}
    if(sig1B$Rank[j] == 3){
      sig1B$Color[j] = "orange"}
    if(sig1B$Rank[j] == 4){
      sig1B$Color[j] = "red"}}
  if(End1_stats$`Average Deficit`[i+1] == max(End1_stats$`Average Deficit`) |
     End1_stats$`Average Deficit`[i+1] == min(End1_stats$`Average Deficit`)){
    vect2 = append(vect2, i+1)}
  vect2 = sort(unique(vect2))
  sig2 = End1_stats[c(vect2),]
  sig2 = sig2 %>%
    mutate("Rank" = 5-rank(sig2$`Average Deficit`))
  sig2["Color"] = NA
  for(j in 1:length(sig2$Rank)){
    if(sig2$Rank[j] == 1){
      sig2$Color[j] = "green"}
    if(sig2$Rank[j] == 2){
      sig2$Color[j] = "yellow"}
    if(sig2$Rank[j] == 3){
      sig2$Color[j] = "orange"}
    if(sig2$Rank[j] == 4){
      sig2$Color[j] = "red"}}
  if(End1_stats$`Average Excess`[i+1] == max(End1_stats$`Average Excess`) |
     End1_stats$`Average Excess`[i+1] == min(End1_stats$`Average Excess`)){
    vect3 = append(vect3, i+1)}
  vect3 = sort(unique(vect3))
  sig3 = End1_stats[c(vect3),]
  sig3 = sig3 %>%
    mutate("Rank" = rank(sig3$`Average Excess`))
  sig3["Color"] = NA
  for(j in 1:length(sig3$Rank)){
    if(sig3$Rank[j] == 1){
      sig3$Color[j] = "green"}
    if(sig3$Rank[j] == 2){
      sig3$Color[j] = "yellow"}
    if(sig3$Rank[j] == 3){
      sig3$Color[j] = "red"}}
  if(End1_stats$`Conditionally Expected Deficit`[i+1] == max(End1_stats$`Conditionally Expected Deficit`) |
     End1_stats$`Conditionally Expected Deficit`[i+1] == min(End1_stats$`Conditionally Expected Deficit`)){
    vect4 = append(vect4, i+1)}
  vect4 = sort(unique(vect4))
  sig4 = End1_stats[c(vect4),]
  sig4 = sig4 %>%
    mutate("Rank" = 5-rank(sig4$`Conditionally Expected Deficit`))
  sig4["Color"] = NA
  for(j in 1:length(sig4$Rank)){
    if(sig4$Rank[j] == 1){
      sig4$Color[j] = "green"}
    if(sig4$Rank[j] == 2){
      sig4$Color[j] = "yellow"}
    if(sig4$Rank[j] == 3){
      sig4$Color[j] = "orange"}
    if(sig4$Rank[j] == 4){
      sig4$Color[j] = "red"}}
  if(End1_stats$`Conditionally Expected Excess`[i+1] == max(End1_stats$`Conditionally Expected Excess`) |
     End1_stats$`Conditionally Expected Excess`[i+1] == min(End1_stats$`Conditionally Expected Excess`)){
    vect5 = append(vect5, i+1)}
  vect5 = sort(unique(vect5))
  sig5 = End1_stats[c(vect5),]
  sig5 = sig5 %>%
    mutate("Rank" = rank(sig5$`Conditionally Expected Excess`))
  sig5["Color"] = NA
  for(j in 1:length(sig5$Rank)){
    if(sig5$Rank[j] == 1){
      sig5$Color[j] = "green"}
    if(sig5$Rank[j] == 2){
      sig5$Color[j] = "yellow"}
    if(sig5$Rank[j] == 3){
      sig5$Color[j] = "red"}}
  if(End1_stats$`Expected Difference`[i+1] == max(End1_stats$`Expected Difference`) |
     End1_stats$`Expected Difference`[i+1] == min(End1_stats$`Expected Difference`)){
    vect6 = append(vect6, i+1)}
  vect6 = sort(unique(vect6))
  sig6 = End1_stats[c(vect6),]
  sig6 = sig6 %>%
    mutate("Rank" = rank(sig6$`Expected Difference`))
  sig6["Color"] = NA
  for(j in 1:length(sig6$Rank)){
    if(sig6$Rank[j] == 1){
      sig6$Color[j] = "green"}
    if(sig6$Rank[j] == 2){
      sig6$Color[j] = "yellow"}
    if(sig6$Rank[j] == 3){
      sig6$Color[j] = "red"}}}
  

a = ggplot(data = End1_stats, aes(x = Std, y = Mean)) +
  geom_point() + 
  geom_label(data=sig0[2,], aes(x = Std+250, y = Mean + 2000,
                                   label = paste0("Smallest Risk: ", Num, "/", 100-Num, "\n",
                                    "SD = ", round(Std, 4))),
             color = "darkgreen", size=4) +
  geom_point(data = sig0, aes(color=Allocation), size=4) +
  scale_color_manual(values = sig0$Color) +
  labs(title = "Mean vs Standard Deviation") +
  ylab("Mean") +
  xlab("Standard Deviation") +
  theme(plot.title = element_text(hjust = 0.5, size =15),
        axis.text = element_text(size = 10),
        axis.title = element_text(size=12),
        strip.text = element_text(size=12),
        legend.position = "right",
        legend.text = element_text(size=10, vjust = 0.5),
        legend.title = element_blank(),
        legend.box = "vertical",
        legend.margin=unit(0, "cm")) +
  guides(color = guide_legend(nrow = 4, byrow = TRUE))

  
b = ggplot(data = End1_stats, aes(x = Num, y = `P[0 < Balalce]`)) +
  geom_point() + 
  geom_label(data=sig1B[2,], aes(x = Num, y = `P[0 < Balalce]`-0.05,
                                   label = paste0("Highest Probability: ", Num, "/", 100-Num, "\n",
                                    "P[0 < Balance] = ", 100 * round(`P[0 < Balalce]`, 4), "%")),
             color = "darkgreen", size=4) +
  geom_point(data = sig1B, aes(color=Allocation), size=4) +
  scale_color_manual(values = sig1B$Color) +
  labs(title = "Fund Sufficiency") +
  ylab("Probability") +
  xlab("Asset Allocation") +
  theme(plot.title = element_text(hjust = 0.5, size =15),
        axis.text = element_text(size = 10),
        axis.title = element_text(size=12),
        strip.text = element_text(size=12),
        legend.position = "right",
        legend.text = element_text(size=10, vjust = 0.5),
        legend.title = element_blank(),
        legend.box = "vertical",
        legend.margin=unit(0, "cm")) +
  guides(color = guide_legend(nrow = 4, byrow = TRUE))

sig4 = sig4 %>%
  mutate("Value" = sig4$`Conditionally Expected Deficit`) %>%
  mutate("Type" = "Deficit")

sig5 = sig5 %>%
  mutate("Value" = sig5$`Conditionally Expected Excess`) %>%
  mutate("Type" = "Surplus")

sig45 = rbind(sig4, sig5)

data1 = End1_stats[, c(1,2,11)]
data2 = End1_stats[, c(1,2,12)]

data1 = data1 %>%
  mutate("Value" = data1$`Conditionally Expected Deficit`) %>%
  mutate("Type" = "Deficit")

data1 = data1[,c(1,2,4,5)]

data2 = data2 %>%
  mutate("Value" = data2$`Conditionally Expected Excess`) %>%
  mutate("Type" = "Surplus")

data2 = data2[,c(1,2,4,5)]

data12 = rbind(data1, data2)

data12["Fill"] = NA
data12$Fill[1:101] = "purple"
data12$Fill[102:202] = "black"


for(i in c(1,2,5,6)){
  levels(sig45$Allocation) <- c(levels(sig45$Allocation), 
                                c(paste0(sig45$Allocation[i], " - (", sig45$Type[i],")")))
  sig45$Allocation[i] = paste0(sig45$Allocation[i], " - (", sig45$Type[i],")")}

sig45["start"] = NA
sig45["unit"] = NA
sig45["nudge_x"] = NA
sig45["nudge_y"] = NA

for(i in c(2,5)){
  if(i == 2){
    sig45$start[i] = "Deficit"
    sig45$unit[i] = "-$"
    sig45$nudge_x[i] = 5
    sig45$nudge_y[i] = 3100}
  if(i == 5){
    sig45$start[i] = "Surplus"
    sig45$unit[i] = "$"
    sig45$nudge_x[i] = 10
    sig45$nudge_y[i] = 2000}}

data12$Fill = factor(data12$Fill, levels = c("purple", "black"))

c = ggplot(data = data12, aes(x = Num, y = Value, color = factor(Type))) +
  geom_point() +
  # geom_point(data = data12[1:101,], aes(x=Num, y=Value), color = "purple") + 
  geom_label(data=sig45[c(2,5),], aes(x = Num + nudge_x, y = nudge_y,
                                   label = paste0("Smallest ", start, ": ", Num, "/", 100-Num, "\n",
                                    "Amount = ", unit, round(abs(Value), 4))),
             color = "darkgreen", size=4) +
  geom_point(data = sig45, aes(x=Num, y = Value, color=Allocation), size=4) +
  scale_color_manual(values =  c("purple", "yellow", "green", "red", "green", "orange", "yellow", "black", "green")) +
  # scale_discrete_manual(aesthetics = c("colour", "fill"), values = c(unique(data12$Fill)), labels = c("Average Deficit", "Average Excess")) +
  labs(title = "Deficit and Surplus Funds") +
  ylab("Amount ($ Millions)") +
  xlab("Asset Allocation") +
  theme(plot.title = element_text(hjust = 0.5, size =15),
        axis.text = element_text(size = 10),
        axis.title = element_text(size=12),
        strip.text = element_text(size=12),
        legend.position = "right",
        legend.text = element_text(size=10, vjust = 0.5),
        legend.title = element_blank(),
        legend.box = "vertical",
        legend.margin=unit(0, "cm")) +
  guides(color = guide_legend(nrow = 9, byrow = TRUE))
  
grid.arrange(a,b,c, ncol=1, top=text_grob("Top-Up", size = 18, face = "bold", hjust = 1.4))


```


```{r}



End_stats = End1_stats %>%
  mutate("Pension" = "Top-Up")

End1_stats = End1_stats %>%
  mutate("Pension" = "Pension")

sig1 = sig1 %>%
  mutate("Pension" = "Pension")

sig1B = sig1B %>%
  mutate("Pension" = "Top-Up")

End2_stats = rbind(End_stats, End1_stats)

sig1B2 = rbind(sig1, sig1B)

d = ggplot(data = End2_stats, aes(x = Num, y = `P[0 < Balalce]`, color = factor(Pension))) +
  geom_point() + 
  geom_label(data=sig1B2[2,], aes(x = Num, y = `P[0 < Balalce]`-0.05,
                                   label = paste0("Highest Probability: ", Num, "/", 100-Num, "\n",
                                    "SD = ", round(`P[0 < Balalce]`, 4))),
             color = "darkgreen", size=4) +
  geom_point(data = sig1B2, aes(color=Allocation), size=4) +
  scale_color_manual(values = sig1B2$Color) +
  labs(title = "Fund Sufficiency") +
  ylab("Probability") +
  xlab("Asset Allocation") +
  theme(plot.title = element_text(hjust = 0.5, size =15),
        axis.text = element_text(size = 10),
        axis.title = element_text(size=12),
        strip.text = element_text(size=12),
        legend.position = "right",
        legend.text = element_text(size=10, vjust = 0.5),
        legend.title = element_blank(),
        legend.box = "vertical",
        legend.margin=unit(0, "cm")) +
  guides(color = guide_legend(nrow = 4, byrow = TRUE))



grid.arrange(d, ncol=1, top=text_grob("Pension vs. Top-Up", size = 18, face = "bold", hjust = 1.4))
```



# Top up 2
```{r, warning=FALSE}

insolvency_rate = 0.0700
for(i in 0:100){
  Top_up2 = Pension
  Top_up2[,2:31] = NA
  Top_up2$Year0 = c(rep(800, 1000)) 
  weight = get(paste0("Weighted_", i))
  for(j in 1:30){
    frame = data.frame(matrix(ncol=2,nrow=1000))
    frame[,1] = c(seq(1,1000,1))
    frame[,2] = c(rep(payments[1,j],1000))
    data = cbind(data.frame(frame[,1]), data.frame(Top_up2[,j]), data.frame(weight[,j]), data.frame(frame[,2]))
    colnames(data) = c("Num", "Last_Year", "Weight", "payment")
    sub1 = subset(data, data$Last_Year > 0)
    sub2 = subset(data, data$Last_Year < 0)
    sub1 = sub1 %>%
      mutate("Balance" = sub1$Last_Year * (1+sub1$Weight) - sub1$payment)
    if(length(sub1$Num) != 1000){
      sub2 = sub2 %>%
        mutate("Balance" = sub2$Last_Year * (1 + insolvency_rate) - sub2$payment)}
    data = rbind(sub1, sub2)
    data_num = order(data$Num)
    data = data[c(data_num),]
    Top_up2[1:1000, j+1] = data$Balance[1:1000]}
  assign(paste0("Top_up2_", i), Top_up2)}
  
for(i in 0:100){
  end2 = get(paste0("Top_up2_", i))
  if(i == 0){
    End2_Balance = data.frame(end2$Year30)}
  if(i != 0){
    End2_Balance = cbind(End2_Balance, data.frame(end2$Year30))}
  colnames(End2_Balance)[i+1] = paste0("Top_up2_", i)}

vect0 = vector()
for(i in 0:100){
  vect0 = append(vect0, paste0("Large Cap: ", i, "% | ", "Fixed: ", 100-i, "%"))}

ci = 0.05*525
End2_stats = data.frame(matrix(nrow = 101, ncol = 13))
colnames(End2_stats) = c("Allocation", "Num", "Mean", "Std", "P[0 < Balalce]", "P[-26.25 < Balalce]", "Average Deficit", "Under_Std", "Average Excess", "Over_Std", "Conditionally Expected Deficit", "Conditionally Expected Excess", "Expected Difference" )
End2_stats$Allocation = c(vect0)
End2_stats$Allocation = factor(End2_stats$Allocation, levels = c(End2_stats$Allocation))
End2_stats$Num = c(seq(0,100,1))

for(i in 0:100){
  End2 = End2_Balance[,i+1]
  end2_under = subset(End2_Balance[, i+1], End2_Balance[, i+1] < 0)
  end2_over = subset(End2_Balance[, i+1], End2_Balance[, i+1] > 0)
  End2_stats$Mean[i+1] = mean(End2)
  End2_stats$Std[i+1] = sqrt(var(End2))
  End2_stats$`P[0 < Balalce]`[i+1] = pnorm(0, mean = End2_stats$Mean[i+1], sd = End2_stats$Std[i+1], lower.tail = FALSE)
  End2_stats$`P[-26.25 < Balalce]`[i+1] = pnorm(-26.25, mean = End2_stats$Mean[i+1], sd = End2_stats$Std[i+1], lower.tail = FALSE)
  End2_stats$`Average Deficit`[i+1] = mean(end2_under)
  End2_stats$Under_Std[i+1] = sqrt(var(end2_under))
  End2_stats$`Average Excess`[i+1] = mean(end2_over)
  End2_stats$Over_Std[i+1] = sqrt(var(end2_over))
  End2_stats$`Conditionally Expected Deficit`[i+1] = End2_stats$`Average Deficit`[i+1] * (1 - End2_stats$`P[0 < Balalce]`)
  End2_stats$`Conditionally Expected Excess`[i+1] = End2_stats$`Average Excess`[i+1] * End2_stats$`P[0 < Balalce]`
  End2_stats$`Expected Difference`[i+1] = End2_stats$`Conditionally Expected Deficit`[i+1] + End2_stats$`Conditionally Expected Excess`[i+1]}

prob = cbind(prob, data.frame(End2_stats[,c(1,2,5)]))
prob = prob[,c(1,2,3,6)]
colnames(prob)[3:4] = c("Pension", "Top-up2")
prob = prob %>%
  mutate("Improvement" = (prob$`Top-up2` - prob$Pension)/prob$Pension)

prob
vect0 = vector()
vect0 = append(vect0, c(1,61,101))
vect1 = vect0
vect2 = vect0
vect3 = vect0
vect4 = vect0
vect5 = vect0
vect6 = vect0
for(i in 0:100){
  if(End2_stats$Std[i+1] == max(End2_stats$Std) |
     End2_stats$Std[i+1] == min(End2_stats$Std)){
    vect0 = append(vect0, i+1)}
  vect0 = sort(unique(vect0))
  sig0 = End2_stats[c(vect0),]
  sig0 = sig0 %>%
    mutate("Rank" = rank(sig0$Std))
  sig0["Color"] = NA
  for(j in 1:length(sig0$Rank)){
    if(sig0$Rank[j] == 1){
      sig0$Color[j] = "green"}
    if(sig0$Rank[j] == 2){
      sig0$Color[j] = "yellow"}
    if(sig0$Rank[j] == 3){
      sig0$Color[j] = "orange"}
    if(sig0$Rank[j] == 4){
      sig0$Color[j] = "red"}}
  if(End2_stats$`P[0 < Balalce]`[i+1] == max(End2_stats$`P[0 < Balalce]`) |
     End2_stats$`P[0 < Balalce]`[i+1] == min(End2_stats$`P[0 < Balalce]`)){
    vect1 = append(vect1, i+1)}
  vect1 = sort(unique(vect1))
  sig1B = End2_stats[c(vect1),]
  sig1B = sig1B %>%
    mutate("Rank" = 5 - rank(sig1B$`P[0 < Balalce]`))
  sig1B["Color"] = NA
  for(j in 1:length(sig1B$Rank)){
    if(sig1B$Rank[j] == 1){
      sig1B$Color[j] = "green"}
    if(sig1B$Rank[j] == 2){
      sig1B$Color[j] = "yellow"}
    if(sig1B$Rank[j] == 3){
      sig1B$Color[j] = "orange"}
    if(sig1B$Rank[j] == 4){
      sig1B$Color[j] = "red"}}
  if(End2_stats$`Average Deficit`[i+1] == max(End2_stats$`Average Deficit`) |
     End2_stats$`Average Deficit`[i+1] == min(End2_stats$`Average Deficit`)){
    vect2 = append(vect2, i+1)}
  vect2 = sort(unique(vect2))
  sig2 = End2_stats[c(vect2),]
  sig2 = sig2 %>%
    mutate("Rank" = 5-rank(sig2$`Average Deficit`))
  sig2["Color"] = NA
  for(j in 1:length(sig2$Rank)){
    if(sig2$Rank[j] == 1){
      sig2$Color[j] = "green"}
    if(sig2$Rank[j] == 2){
      sig2$Color[j] = "yellow"}
    if(sig2$Rank[j] == 3){
      sig2$Color[j] = "orange"}
    if(sig2$Rank[j] == 4){
      sig2$Color[j] = "red"}}
  if(End2_stats$`Average Excess`[i+1] == max(End2_stats$`Average Excess`) |
     End2_stats$`Average Excess`[i+1] == min(End2_stats$`Average Excess`)){
    vect3 = append(vect3, i+1)}
  vect3 = sort(unique(vect3))
  sig3 = End2_stats[c(vect3),]
  sig3 = sig3 %>%
    mutate("Rank" = rank(sig3$`Average Excess`))
  sig3["Color"] = NA
  for(j in 1:length(sig3$Rank)){
    if(sig3$Rank[j] == 1){
      sig3$Color[j] = "green"}
    if(sig3$Rank[j] == 2){
      sig3$Color[j] = "yellow"}
    if(sig3$Rank[j] == 3){
      sig3$Color[j] = "red"}}
  if(End2_stats$`Conditionally Expected Deficit`[i+1] == max(End2_stats$`Conditionally Expected Deficit`) |
     End2_stats$`Conditionally Expected Deficit`[i+1] == min(End2_stats$`Conditionally Expected Deficit`)){
    vect4 = append(vect4, i+1)}
  vect4 = sort(unique(vect4))
  sig4 = End2_stats[c(vect4),]
  sig4 = sig4 %>%
    mutate("Rank" = 5-rank(sig4$`Conditionally Expected Deficit`))
  sig4["Color"] = NA
  for(j in 1:length(sig4$Rank)){
    if(sig4$Rank[j] == 1){
      sig4$Color[j] = "green"}
    if(sig4$Rank[j] == 2){
      sig4$Color[j] = "yellow"}
    if(sig4$Rank[j] == 3){
      sig4$Color[j] = "orange"}
    if(sig4$Rank[j] == 4){
      sig4$Color[j] = "red"}}
  if(End2_stats$`Conditionally Expected Excess`[i+1] == max(End2_stats$`Conditionally Expected Excess`) |
     End2_stats$`Conditionally Expected Excess`[i+1] == min(End2_stats$`Conditionally Expected Excess`)){
    vect5 = append(vect5, i+1)}
  vect5 = sort(unique(vect5))
  sig5 = End2_stats[c(vect5),]
  sig5 = sig5 %>%
    mutate("Rank" = rank(sig5$`Conditionally Expected Excess`))
  sig5["Color"] = NA
  for(j in 1:length(sig5$Rank)){
    if(sig5$Rank[j] == 1){
      sig5$Color[j] = "green"}
    if(sig5$Rank[j] == 2){
      sig5$Color[j] = "yellow"}
    if(sig5$Rank[j] == 3){
      sig5$Color[j] = "red"}}
  if(End2_stats$`Expected Difference`[i+1] == max(End2_stats$`Expected Difference`) |
     End2_stats$`Expected Difference`[i+1] == min(End2_stats$`Expected Difference`)){
    vect6 = append(vect6, i+1)}
  vect6 = sort(unique(vect6))
  sig6 = End2_stats[c(vect6),]
  sig6 = sig6 %>%
    mutate("Rank" = rank(sig6$`Expected Difference`))
  sig6["Color"] = NA
  for(j in 1:length(sig6$Rank)){
    if(sig6$Rank[j] == 1){
      sig6$Color[j] = "green"}
    if(sig6$Rank[j] == 2){
      sig6$Color[j] = "yellow"}
    if(sig6$Rank[j] == 3){
      sig6$Color[j] = "red"}}}
  

a = ggplot(data = End2_stats, aes(x = Std, y = Mean)) +
  geom_point() + 
  geom_label(data=sig0[2,], aes(x = Std+250, y = Mean + 2000,
                                   label = paste0("Smallest Risk: ", Num, "/", 100-Num, "\n",
                                    "SD = ", round(Std, 4))),
             color = "darkgreen", size=4) +
  geom_point(data = sig0, aes(color=Allocation), size=4) +
  scale_color_manual(values = sig0$Color) +
  labs(title = "Mean vs Standard Deviation") +
  ylab("Mean") +
  xlab("Standard Deviation") +
  theme(plot.title = element_text(hjust = 0.5, size =15),
        axis.text = element_text(size = 10),
        axis.title = element_text(size=12),
        strip.text = element_text(size=12),
        legend.position = "right",
        legend.text = element_text(size=10, vjust = 0.5),
        legend.title = element_blank(),
        legend.box = "vertical",
        legend.margin=unit(0, "cm")) +
  guides(color = guide_legend(nrow = 4, byrow = TRUE))

  
b = ggplot(data = End2_stats, aes(x = Num, y = `P[0 < Balalce]`)) +
  geom_point() + 
  geom_label(data=sig1B[2,], aes(x = Num, y = `P[0 < Balalce]`-0.05,
                                   label = paste0("Highest Probability: ", Num, "/", 100-Num, "\n",
                                    "P[0 < Balance] = ", 100 * round(`P[0 < Balalce]`, 4), "%")),
             color = "darkgreen", size=4) +
  geom_point(data = sig1B, aes(color=Allocation), size=4) +
  scale_color_manual(values = sig1B$Color) +
  labs(title = "Fund Sufficiency") +
  ylab("Probability") +
  xlab("Asset Allocation") +
  theme(plot.title = element_text(hjust = 0.5, size =15),
        axis.text = element_text(size = 10),
        axis.title = element_text(size=12),
        strip.text = element_text(size=12),
        legend.position = "right",
        legend.text = element_text(size=10, vjust = 0.5),
        legend.title = element_blank(),
        legend.box = "vertical",
        legend.margin=unit(0, "cm")) +
  guides(color = guide_legend(nrow = 4, byrow = TRUE))

sig4 = sig4 %>%
  mutate("Value" = sig4$`Conditionally Expected Deficit`) %>%
  mutate("Type" = "Deficit")

sig5 = sig5 %>%
  mutate("Value" = sig5$`Conditionally Expected Excess`) %>%
  mutate("Type" = "Surplus")

sig45 = rbind(sig4, sig5)

data1 = End2_stats[, c(1,2,11)]
data2 = End2_stats[, c(1,2,12)]

data1 = data1 %>%
  mutate("Value" = data1$`Conditionally Expected Deficit`) %>%
  mutate("Type" = "Deficit")

data1 = data1[,c(1,2,4,5)]

data2 = data2 %>%
  mutate("Value" = data2$`Conditionally Expected Excess`) %>%
  mutate("Type" = "Surplus")

data2 = data2[,c(1,2,4,5)]

data12 = rbind(data1, data2)

data12["Fill"] = NA
data12$Fill[1:101] = "purple"
data12$Fill[102:202] = "black"


for(i in c(1,2,5,6)){
  levels(sig45$Allocation) <- c(levels(sig45$Allocation), 
                                c(paste0(sig45$Allocation[i], " - (", sig45$Type[i],")")))
  sig45$Allocation[i] = paste0(sig45$Allocation[i], " - (", sig45$Type[i],")")}

sig45["start"] = NA
sig45["unit"] = NA
sig45["nudge_x"] = NA
sig45["nudge_y"] = NA

for(i in c(2,5)){
  if(i == 2){
    sig45$start[i] = "Deficit"
    sig45$unit[i] = "-$"
    sig45$nudge_x[i] = 5
    sig45$nudge_y[i] = 3100}
  if(i == 5){
    sig45$start[i] = "Surplus"
    sig45$unit[i] = "$"
    sig45$nudge_x[i] = 10
    sig45$nudge_y[i] = 2000}}

data12$Fill = factor(data12$Fill, levels = c("purple", "black"))

c = ggplot(data = data12, aes(x = Num, y = Value, color = factor(Type))) +
  geom_point() +
  # geom_point(data = data12[1:101,], aes(x=Num, y=Value), color = "purple") + 
  geom_label(data=sig45[c(2,5),], aes(x = Num + nudge_x, y = nudge_y,
                                   label = paste0("Smallest ", start, ": ", Num, "/", 100-Num, "\n",
                                    "Amount = ", unit, round(abs(Value), 4))),
             color = "darkgreen", size=4) +
  geom_point(data = sig45, aes(x=Num, y = Value, color=Allocation), size=4) +
  scale_color_manual(values =  c("purple", "yellow", "green", "red", "green", "orange", "yellow", "black", "green")) +
  # scale_discrete_manual(aesthetics = c("colour", "fill"), values = c(unique(data12$Fill)), labels = c("Average Deficit", "Average Excess")) +
  labs(title = "Deficit and Surplus Funds") +
  ylab("Amount ($ Millions)") +
  xlab("Asset Allocation") +
  theme(plot.title = element_text(hjust = 0.5, size =15),
        axis.text = element_text(size = 10),
        axis.title = element_text(size=12),
        strip.text = element_text(size=12),
        legend.position = "right",
        legend.text = element_text(size=10, vjust = 0.5),
        legend.title = element_blank(),
        legend.box = "vertical",
        legend.margin=unit(0, "cm")) +
  guides(color = guide_legend(nrow = 9, byrow = TRUE))
  
grid.arrange(a,b,c, ncol=1, top=text_grob("Top-up2", size = 18, face = "bold", hjust = 1.4))
```